### ISSUE TITLE
Exception occurs under python 3.10

### ISSUE THREAD

**Issue by wmkai** [google/yapf#1009]
```
2022-06-07 16:38:16,092 - mmcls - INFO - initialize LinearClsHead with init_cfg {'type': 'Normal', 'layer': 'Linear', 'std': 0.01}     
Traceback (most recent call last):                                             
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)                      
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)     
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):                               
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)                       
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (315, 36))                                                                                                

During handling of the above exception, another exception occurred:           
                                                                                                                                                               
Traceback (most recent call last):                                             
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)                                   
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):                                           
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken                                                                          
    raise ParseError("bad input", type, value, context)                                    
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (315, 36))                                                                                                

During handling of the above exception, another exception occurred:                        

Traceback (most recent call last):           
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode                                                        
    tree = pytree_utils.ParseCodeToTree(unformatted_source)                                
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 131, in ParseCodeToTree                                               
    raise e                                  
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 129, in ParseCodeToTree                                               
    ast.parse(code)                          
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/ast.py", line 50, in parse                                                                                              
    return compile(source, filename, mode, flags,                                          
  File "<unknown>", line 315                 
    activations=<class 'torch.nn.modules.activation.ReLU'>),                               
                ^                            
SyntaxError: invalid syntax                  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):           
  File "/home/tiger/code/mmrazor/tools/mmcls/train_mmcls.py", line 203, in <module>                                                                                                   
    main()                                   
  File "/home/tiger/code/mmrazor/tools/mmcls/train_mmcls.py", line 186, in main                                                                                                       
    config=cfg.pretty_text,                  
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/mmcv/utils/config.py", line 508, in pretty_text                                                           
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)                       
  File "/home/tiger/miniconda3/envs/open-mmlab/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode                                                        
    raise errors.YapfError(errors.FormatErrorMsg(e))                                       
yapf.yapflib.errors.YapfError: <unknown>:315:37: invalid syntax                            
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 718949) of binary: /home/tiger/miniconda3/envs/open-mmlab/bin/python
tools/mmcls/dist_train.sh: line 19: 718941 Segmentation fault      (core dumped) PYTHONPATH="$(dirname $0)/../..":$PYTHONPATH python -m torch.distributed.launch --nnodes=$NNODES --no
de_rank=$NODE_RANK --master_addr=$MASTER_ADDR --nproc_per_node=$GPUS --master_port=29501 $(dirname "$0")/train_mmcls.py $CONFIG --launcher pytorch ${@:3}
```
I don't know why and hope to get help

**Comment by Huiimin5** [comment]
Hi, how did you fix this issue? Many thanks.
