### ISSUE TITLE
Returning a unpacked tuple with asterisk results in ParseError

### ISSUE THREAD

**Issue by gaotongxiao** [google/yapf#1060]
Here is the shortest code snippet for reproducing the error:

```python
def a():
  t = (2, 3)
  return *t
```

Running yapf on it will result in the error: `lib2to3.pgen2.parse.ParseError: bad input: type=16, value='*', context=(' ', (3, 11))`.

**Comment by mpf82** [comment]
You should probably state which version of Python / yapf you are using.

Interstingly, if I use the following as input:

```python
def a():
  t=(2,3)
  return *t
```

yapf (0.32.0) with Python 3.9 will output:

```python
def a():
    t = (2, 3)
    return *t
```

So it seems, yapf can handle this.

But if I try to actually run the module in Python, I the a Syntax error:

```
  File "test.py", line 3
    return *t
           ^^
SyntaxError: can't use starred expression here
```

**Comment by gaotongxiao** [comment]
I'm using python 3.8.15 + yapf 0.32.0.

The code snippet doesn't quite make sense because I have tested out several cases and tried to locate the reason. Use the following syntactically correct snippet can also reproduce this error:

```python
def a():
    t = (2, 3)
    for i in range(5):
      yield i, *t
```

Here is the full traceback:

```bash
Traceback (most recent call last):
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=16, value='*', context=(' ', (4, 15))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=16, value='*', context=(' ', (4, 15))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/__init__.py", line 225, in _FormatFile
    reformatted_code, encoding, has_change = yapf_api.FormatFile(
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 96, in FormatFile
    reformatted_source, changed = FormatCode(
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nvme/test/anaconda3/envs/refactor/bin/yapf", line 8, in <module>
    sys.exit(run_main())
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/__init__.py", line 360, in run_main
    sys.exit(main(sys.argv))
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/__init__.py", line 124, in main
    changed = FormatFiles(
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/__init__.py", line 202, in FormatFiles
    changed |= _FormatFile(filename, lines, style_config, no_local_style,
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/__init__.py", line 236, in _FormatFile
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/nvme/test/anaconda3/envs/refactor/lib/python3.8/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
```
