### ISSUE TITLE
Parenthesized context managers throwing exception

### ISSUE THREAD

**Issue by flamingbear** [google/yapf#1064]
I looked for a similar ticket, but can't find it.

Test file with parenthesized context managers is throwing an error

python = 3.10.9
yapf = 0.32.0
 
UPDATE:
I think this is working with black and autopep8. But I can also see this is a parser error happening.

``` python
def test_copy_dimension(self):
    with (Dataset() as target_ds,
          Dataset() as source_ds):
        do_something

```

or on one line.

``` python
def test_copy_dimension(self):
    with (Dataset() as target_ds, Dataset() as source_ds):
        pass

```

running basic yapf casues an exception

``` bash
yapf testfile.py
Traceback (most recent call last):
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Users/savoie/.pyenv/versions/3.10.9/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Users/savoie/.pyenv/versions/3.10.9/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Users/savoie/.pyenv/versions/3.10.9/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='as', context=(' ', (9, 20))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Users/savoie/.pyenv/versions/3.10.9/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Users/savoie/.pyenv/versions/3.10.9/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Users/savoie/.pyenv/versions/3.10.9/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='as', context=(' ', (9, 20))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/__init__.py", line 225, in _FormatFile
    reformatted_code, encoding, has_change = yapf_api.FormatFile(
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 96, in FormatFile
    reformatted_source, changed = FormatCode(
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/bin/yapf", line 8, in <module>
    sys.exit(run_main())
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/__init__.py", line 360, in run_main
    sys.exit(main(sys.argv))
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/__init__.py", line 124, in main
    changed = FormatFiles(
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/__init__.py", line 202, in FormatFiles
    changed |= _FormatFile(filename, lines, style_config, no_local_style,
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/__init__.py", line 236, in _FormatFile
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/Users/savoie/.pyenv/versions/harmony-regridding-service/lib/python3.10/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range
```

Let me know if I can provide any more information.

**Comment by Spitfire1900** [comment]
#1067 adds support for this.
