### ISSUE TITLE
stdin input breaks with indented input

### ISSUE THREAD

**Issue by alexjurkiewicz** [google/yapf#110]
```shell
echo "    a = 'hi'" | yapf
```

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 9, in <module>
    load_entry_point('yapf==0.1.4', 'console_scripts', 'yapf')()
  File "/Library/Python/2.7/site-packages/yapf/__init__.py", line 183, in run_main
    sys.exit(main(sys.argv))
  File "/Library/Python/2.7/site-packages/yapf/__init__.py", line 116, in main
    verify=args.verify))
  File "/Library/Python/2.7/site-packages/yapf/yapflib/yapf_api.py", line 101, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Library/Python/2.7/site-packages/yapf/yapflib/pytree_utils.py", line 100, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=5, value=u'    ', context=(u'', (1, 0))
```

**Comment by gwelymernans** [comment]
This is a limitation due to how things are parsed. We make an assumption that the program is well-formed, so the example you gave is technically invalid. I'm not sure how to resolve this issue. lib2to3's parser won't parse that, and I'm not aware of a "fuzzy" parser for Python that would accept snippets like that.

I'm open to ideas that people have...

**Comment by alexjurkiewicz** [comment]
My use-case is that I'm copy-pasting snippets of code from a larger program to see what happens to them. Perhaps you could special-case stdin to strip the same amount of whitespace from the first line from all subsequent lines?

**Comment by gwelymernans** [comment]
I thought about that. It's a possibility, but there are still limitations. For example, this code would still fail:

```
    a = 42
try:
    b = 37
finally:
    print('hello world')
```

And once we go down the road of modifying the code, we will almost certainly hit situations that caused us to turn off `--verify` by default. (I.e., it causes more problems than it solves.) So I'm hesitant to do that.

**Comment by alexjurkiewicz** [comment]
Yeah, I can't see anything to be done in that circumstance except erroring
out. Perhaps you could try the simple approach and give up if it fails?

**Comment by hayd** [comment]
I think failing and returning non-zero exit status is what you want. My solution for this is to raise and give an informative error message (in python 2 you won't see the top two errors).

```
Traceback (most recent call last):
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/site-packages/yapf-0.1.5-py3.4.egg/yapf/yapflib/pytree_utils.py", line 101, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=5, value='    ', context=('', (1, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/site-packages/yapf-0.1.5-py3.4.egg/yapf/yapflib/pytree_utils.py", line 107, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=5, value='    ', context=('', (1, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yapf/__init__.py", line 213, in <module>
    run_main()
  File "yapf/__init__.py", line 209, in run_main
    sys.exit(main(sys.argv))
  File "yapf/__init__.py", line 145, in main
    verify=args.verify)
  File "yapf/__init__.py", line 175, in FormatFiles
    verify=verify)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/site-packages/yapf-0.1.5-py3.4.egg/yapf/yapflib/yapf_api.py", line 76, in FormatFile
    verify=verify)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/site-packages/yapf-0.1.5-py3.4.egg/yapf/yapflib/yapf_api.py", line 101, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/site-packages/yapf-0.1.5-py3.4.egg/yapf/yapflib/pytree_utils.py", line 113, in ParseCodeToTree
    raise(e)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/site-packages/yapf-0.1.5-py3.4.egg/yapf/yapflib/pytree_utils.py", line 111, in ParseCodeToTree
    ast.parse(code)
  File "/Users/andy/anaconda/envs/py34/lib/python3.4/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "bad.py", line 1
    a = 42
    ^
IndentationError: unexpected indent
```

---

> My use-case is that I'm copy-pasting snippets of code from a larger program to see what happens to them.

IMO getting a SyntaxError seems a reasonable thing to happen. I think stripping the whitespace (which you can do with `textwrap.dedent`) is a little magical, and you should do as the caller. :)

**Comment by gwelymernans** [comment]
I have to admit that after thinking about it, I'm more likely to agree with @hayd. If we modify the whitespace, then we need to modify the column limit, and then indent the reformatted text, which I don't think `textwrap` can do.

I'm going to close this out. If you feel strongly about it, please let me know. I would gladly accept contributions to do this. :-)
