### ISSUE TITLE
yapf fails to parse legal `@lambda _: _()` decorator

### ISSUE THREAD

**Issue by samuela** [google/yapf#1116]
Running yapf on the following file:
```py
@lambda _: _()
def foo():
    return 1 + 2
```
gives me the error:
```
❯ ns -p yapf --run "yapf -i yapf-bug.py"
Traceback (most recent call last):
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='lambda', context=('', (1, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='lambda', context=('', (1, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/__init__.py", line 225, in _FormatFile
    reformatted_code, encoding, has_change = yapf_api.FormatFile(
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 96, in FormatFile
    reformatted_source, changed = FormatCode(
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/bin/.yapf-wrapped", line 9, in <module>
    sys.exit(run_main())
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/__init__.py", line 360, in run_main
    sys.exit(main(sys.argv))
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/__init__.py", line 124, in main
    changed = FormatFiles(
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/__init__.py", line 202, in FormatFiles
    changed |= _FormatFile(filename, lines, style_config, no_local_style,
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/__init__.py", line 236, in _FormatFile
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/nix/store/n0kcajx0qc3ylgdjswcnn53d5k48jk2l-python3.10-yapf-0.32.0/lib/python3.10/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range
```
despite the input code being entirely valid:
```
❯ python3 yapf-bug.py   
❯ echo $?             
0
```

I'm on yapf version 0.32.0.

**Comment by bwendling** [comment]
Try the newest yapf to see if this has been fixed. The parser was redone to support new Python syntaxes.

**Comment by Spitfire1900** [comment]
Look like this can be closed :smile:
