### ISSUE TITLE
Windows (64-bit): FileNotFoundError: style.yapf

### ISSUE THREAD

**Issue by ndunn219** [google/yapf#140]
When I invoke yapf using yapf 1.py, where 1.py is the file name, I get this error:

  File "C:\Python34\lib\genericpath.py", line 19, in exists os.stat(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\.style.yapf'

While it's handling that exceptions occur, starting with this one:
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main  "__main__", mod_spec)

**Comment by gwelymernans** [comment]
@sbc100 & @eliben any ideas on this?

**Comment by eliben** [comment]
@ndunn219 a full invocatin line and the full stack trace would be helpful.

Unfortunately I don't have access to a Windows machine to test this. @sbc100 do you?

**Comment by sbc100** [comment]
Yes, I have a windows box.  I can take a look at this on Monday.  Looks like it could be a bug in genericpath.py, although that seems very unlikely:
http://apt-browse.org/browse/ubuntu/trusty/main/amd64/libpython3.4-minimal/3.4.0-2ubuntu1/file/usr/lib/python3.4/genericpath.py

os.path.exists() is calling os.stat() can trying to catch exceptions, but its catching OSError and I guess WinError is not a subclass?

**Comment by ndunn219** [comment]
Thanks, all. Is this what you need?

C:\...\generators>yapf 1.py
Traceback (most recent call last):
  File "C:\Python34\lib\genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\.style.yapf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\yapf.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\yapf\__init__.py", line 222, in run_main
    sys.exit(main(sys.argv))
  File "C:\Python34\lib\site-packages\yapf\__init__.py", line 153, in main
    verify=args.verify)
  File "C:\Python34\lib\site-packages\yapf\__init__.py", line 182, in FormatFiles
    style_config = file_resources.GetDefaultStyleForDir(os.path.dirname(filename))
  File "C:\Python34\lib\site-packages\yapf\yapflib\file_resources.py", line 37,in GetDefaultStyleForDir
    if os.path.exists(style_file):
  File "C:\Python34\lib\genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt

**Comment by gwelymernans** [comment]
Ping?

**Comment by hayd** [comment]
I wonder if this was fixed by #156 (noticing the KeyboardInterrupt).

**Comment by ndunn219** [comment]
Yes! It works now! Thanks!
