### ISSUE TITLE
Exception when formatting list comprehensions on Python 3

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#15]
The following code causes an error when yapf is run under python 3 (I've tried on both 3.2 and 3.4):

    def given(y):
        [k for k in () if k in y]

It gives the following error:

    Traceback (most recent call last):
      File "/home/david/.pyenv/versions/3.4.2/bin/yapf", line 11, in <module>
        sys.exit(run_main())
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/__init__.py", line 154, in run_main
        sys.exit(main(sys.argv))
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/__init__.py", line 102, in main
        print_diff=args.diff)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/__init__.py", line 124, in FormatFiles
        filename, style_config=style_config, lines=lines, print_diff=print_diff)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/yapflib/yapf_api.py", line 68, in FormatFile
        print_diff=print_diff)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/yapflib/yapf_api.py", line 101, in FormatCode
        uwl.CalculateFormattingInformation()
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/yapflib/unwrapped_line.py", line 77, in CalculateFormattingInformation
        token.split_penalty += _SplitPenalty(prev_token, token)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/site-packages/yapf/yapflib/unwrapped_line.py", line 342, in _SplitPenalty
        if cur_token.node_split_penalty > 0:
    TypeError: unorderable types: NoneType() > int()

I've tried this both against the latest version on pip and the current version of master.

**Comment by eliben** [comment]
@DRMacIver Thanks for the report!

I can't reproduce this though, with Python 3.4 -- are you sure you synced the ``master`` branch to latest? (Note that we don't really support a pip release now -- someone just uploaded a really old version on PyPI)

I added a test for this in https://github.com/google/yapf/commit/3756f78ed1128daaeab0e509085efa13c9a860f2 -- it should pass

**Comment by DRMacIver** [comment]
Beg your pardon. You're quite right - I can't reproduce it on head now either. I think I must have done something silly earlier. 

I've rerun it against the original examples that produced this to make sure that it's not that I just accidentally oversimplified the example and was fooled into thinking it still broke, and that passes now, so 

The rest of my examples (except maybe the earliest couple) should all be against the real version of master FWIW as I uninstalled the pip version to make sure to not have this sort of mistake.
