### ISSUE TITLE
Distinguish between invalid and formatted code

### ISSUE THREAD

**Issue by joaodelgado** [google/yapf#186]
Since 0.2.8, yapf exits with code 1 if running it resulted in a modified code.

Unfortunately, 1 is also the exit code of an uncaught exception, in particular, the SyntaxError raised when using the --verify flag.

This makes it harder to distinguish, in a script, between a successful operation (source code was successfully formatted) and an error.

**Comment by gwelymernans** [comment]
Ah! Yes. Thanks for catching that. The best(?) way to do this in light of the other change is to return a different value in the case of an error. That way your script can detect it. Something like:

```
if ! yapf /tmp/foo.py > /dev/null 2>&1 ; then
  if [ $? == 2 ]; then
    # Something bad happened
  else
    # There was a syntactically correct change.
  fi
fi
```

I added that with 

```
To https://github.com/google/yapf.git
   9adfa0c..f2b6978  master -> master
```

Please let me know if that works for you.

**Comment by joaodelgado** [comment]
Unfortunately, it doesn't solve my problem

f2b6978 only returns 2 when catching a `YapfError` and, from what I could gather, this is only raised on a cli error.

My particular use case involves passing invalid python to yapf.
In this case, yapf halts with a SyntaxError that is raised by [`ParseCodeToTree`](https://github.com/google/yapf/blob/master/yapf/yapflib/pytree_utils.py#L109-L114)

```
$ echo "invalid python code" | yapf; echo $?                                                                                                                                   
Traceback (most recent call last):
  File "/home/joao/projects/yapf/yapf/yapflib/pytree_utils.py", line 100, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.4/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='python', context=(' ', (1, 8))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joao/projects/yapf/yapf/yapflib/pytree_utils.py", line 106, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.4/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='python', context=(' ', (1, 8))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joao/projects/yapf/env/bin/yapf", line 9, in <module>
    load_entry_point('yapf==0.2.9', 'console_scripts', 'yapf')()
  File "/home/joao/projects/yapf/yapf/__init__.py", line 231, in run_main
    sys.exit(main(sys.argv))
  File "/home/joao/projects/yapf/yapf/__init__.py", line 142, in main
    verify=args.verify)
  File "/home/joao/projects/yapf/yapf/yapflib/yapf_api.py", line 123, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/joao/projects/yapf/yapf/yapflib/pytree_utils.py", line 112, in ParseCodeToTree
    raise e
  File "/home/joao/projects/yapf/yapf/yapflib/pytree_utils.py", line 110, in ParseCodeToTree
    ast.parse(code)
  File "/usr/lib/python3.4/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    invalid python code
                 ^
SyntaxError: invalid syntax
1
```

My suggestion is to change the exit code for when the source code was correctly formatted to something different then 1, since this is the exit code used by python when an unexpected error occurs.
This way it would be more predictable to know when yapf worked as expected or something went wrong.

**Comment by gwelymernans** [comment]
Hrm. Okay. I switched the values then. I hope this helps!

**Comment by joaodelgado** [comment]
Yup. It solves all my issues!

Thank you!

**Comment by a-sk** [comment]
Could you, please, make a new release with this new behaviour.

**Comment by gwelymernans** [comment]
@a-sk would it be okay to wait until Thursday or Friday? I normally like to combine multiple changes per release if possible...

**Comment by a-sk** [comment]
Sure, no problem, thanks!
