### ISSUE TITLE
yapf fails with "Invalid Syntax" combining print_function with twisted callbacks

### ISSUE THREAD

**Issue by jamesbroadhead** [google/yapf#226]
yapf rejects some well-formed python files which use the print_function as twisted callbacks. 

This failure occurs inconsistently -- possibly due to passing a list of targets, only some of which do the print_function import (I have not been able to shareably reproduce the inconsistency)

```
#!/usr/bin/env python
from __future__ import print_function
from twisted.internet import defer, reactor

def main():
    d = defer.succeed("hi")
    d.addCallback(print) # <=== this
    d.addBoth(lambda _: reactor.stop())
    return d

if __name__ == '__main__':
    reactor.callWhenRunning(main)
    reactor.run()
```

```
  $ pyflakes the_file.py   # <passes> 
  $ ./the_file.py 
  hi
```

```
  Traceback (most recent call last):
    File "/home/jbroadhead/venv/tdi/bin/yapf", line 9, in <module>
      load_entry_point('yapf==0.6.2', 'console_scripts', 'yapf')()
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/__init__.py", line 250, in run_main
      sys.exit(main(sys.argv))
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/__init__.py", line 168, in main
      verify=args.verify)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/__init__.py", line 212, in FormatFiles
      logger=logging.warning)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 91, in FormatFile
      verify=verify)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 141, in FormatCode
      reformatted_source = reformatter.Reformat(uwlines, verify)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/reformatter.py", line 108, in Reformat
      verifier.VerifyCode(formatted_code[-1])
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/verifier.py", line 52, in VerifyCode
      raise InternalError(sys.exc_info()[1])
  yapf.yapflib.verifier.InternalError: invalid syntax (<string>, line 1)
```

**Comment by gwelymernans** [comment]
I'm very sorry. I didn't see this until now. :-(

You seem to be using the `--verify` flag. That's not really a good option for production, because it's mostly meant for debugging purposes.

**Comment by skyler9901** [comment]
Hi,Did you handle the problem? Now i encounter the same problem.
