### ISSUE TITLE
yapf does not print the filename when it fails to parse a file

### ISSUE THREAD

**Issue by jamesbroadhead** [google/yapf#227]
When yapf fails to fomat a file, it returns an exception trace to the user. Instead, it should log the trace, and print the name of the file(s) which failed to be formatted. 

Opinion: it should continue to format all the files passed, returning a list of failed targets once complete

````
  Traceback (most recent call last):
    File "/home/jbroadhead/venv/tdi/bin/yapf", line 9, in <module>
      load_entry_point('yapf==0.6.2', 'console_scripts', 'yapf')()
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/__init__.py", line 250, in run_main
      sys.exit(main(sys.argv))
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/__init__.py", line 168, in main
      verify=args.verify)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/__init__.py", line 212, in FormatFiles
      logger=logging.warning)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 91, in FormatFile
      verify=verify)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 141, in FormatCode
      reformatted_source = reformatter.Reformat(uwlines, verify)
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/reformatter.py", line 108, in Reformat
      verifier.VerifyCode(formatted_code[-1])
    File "/home/jbroadhead/venv/tdi/local/lib/python2.7/site-packages/yapf/yapflib/verifier.py", line 52, in VerifyCode
      raise InternalError(sys.exc_info()[1])
  yapf.yapflib.verifier.InternalError: invalid syntax (<string>, line 1)
````

**Comment by gwelymernans** [comment]
First off, you probably shouldn't use the `--verify` option. It's mostly for debugging. :-)

Right now, YAPF should be logging failures to format. If you're using `--verify`, could you try running without that and see how it goes?

**Comment by jamesbroadhead** [comment]
Yep -- re-using the example code from #226, without --verify returns successfully. 

If --verify is only for debugging, that should be documented -- I read it as "you should set this in prod to confirm that yapf is working correctly"

**Comment by gwelymernans** [comment]
I'll document it better. Thanks!
