### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by gene1224** [google/yapf#246]
`rangrang@rangrang:~/Desktop/Ingenuity Project$ yapf 
Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 7, in <module>
    from yapf import run_main
  File "/usr/local/lib/python2.7/dist-packages/yapf/__init__.py", line 39, in <module>
    from yapf.yapflib import yapf_api
  File "/usr/local/lib/python2.7/dist-packages/yapf/yapflib/yapf_api.py", line 41, in <module>
    from yapf.yapflib import blank_line_calculator
  File "/usr/local/lib/python2.7/dist-packages/yapf/yapflib/blank_line_calculator.py", line 28, in <module>
    from yapf.yapflib import pytree_utils
  File "/usr/local/lib/python2.7/dist-packages/yapf/yapflib/pytree_utils.py", line 75, in <module>
    _GRAMMAR_FOR_PY3 = pygram.python_grammar_no_print_statement.copy()
AttributeError: 'module' object has no attribute 'python_grammar_no_print_statement'
`

**Comment by gwelymernans** [comment]
I'm not sure what's going on here. If your copy of `lib2to3` doesn't have `python_grammar_no_print_statement`, then it sounds like it's not a proper installation of `lib2to3`...
