### ISSUE TITLE
SyntaxError while formatting

### ISSUE THREAD

**Issue by ChillarAnand** [google/yapf#265]
```
$ cat test.py
y = 1





z =
```
Simple file: test.py

When I try to format this, yapf is throwing syntax error.

```
$ yapf test.py
Traceback (most recent call last):
  File "/home/anand/.virtualenvs/exp/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/yapf/__init__.py", line 248, in run_main
    sys.exit(main(sys.argv))
  File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/yapf/__init__.py", line 166, in main
    verify=args.verify)
  File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/yapf/__init__.py", line 210, in FormatFiles
    logger=logging.warning)
  File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 89, in FormatFile
    verify=verify)
  File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 122, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/yapf/yapflib/pytree_utils.py", line 113, in ParseCodeToTree
    raise e
  File "test.py", line 7
    z =
      ^
SyntaxError: invalid syntax
```

Autopep8 seems to fix it without any issues?

```
$ autopep8 test.py
y = 1


z =
```

Can yapf do the same?

**Comment by gwelymernans** [comment]
`autopep8` isn't able to reformat this code. Instead, it's returning the source unmodified.  `yapf` just informs the user that the source is invalid in some way. But the end result is basically the same: the code isn't reformatted. I'm not sure if returning the unmodified source is better in this case...

**Comment by ChillarAnand** [comment]
In the original file, there are several blank lines between start & end line. However autopep8 reduced them to two lines?

**Comment by ChillarAnand** [comment]
You can also see this https://github.com/jorgenschaefer/elpy/issues/901

**Comment by gwelymernans** [comment]
Hmm...weird. The code in `autopep8` appears to return the same source if there's a parse error. I'm not sure why it removed the extra lines, though. It might be some kind of `lib2to3` magic. Anyway, `yapf` won't be able to perform any reformatting, because we don't have the parse tree available to us. Would it solve / help jorgenschaefer/elpy#901 to return the unmodified source in the case of a syntax error?

**Comment by ChillarAnand** [comment]
We have already implemented try catch for yapf. 

I think it is better to throw syntax error instead returning original code?
