### ISSUE TITLE
Comment between two decorators produces internal error

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#27]
The following:

    def foo(x):
        return x

    @foo
    # A comment
    @foo
    def inner(self):
        pass

Produces the following error:

    INTERNAL ERROR: 
    # A comment
    @foo
    Traceback (most recent call last):
      File "/home/david/.pyenv/versions/2.7.8/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/home/david/.pyenv/versions/2.7.8/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/david/yapf/yapf/__main__.py", line 18, in <module>
        sys.exit(yapf.main(sys.argv))
      File "/home/david/yapf/yapf/__init__.py", line 102, in main
        print_diff=args.diff)
      File "/home/david/yapf/yapf/__init__.py", line 124, in FormatFiles
        filename, style_config=style_config, lines=lines, print_diff=print_diff)
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 67, in FormatFile
        print_diff=print_diff)
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 110, in FormatCode
        reformatted_source = reformatter.Reformat(uwlines)
      File "/home/david/yapf/yapf/yapflib/reformatter.py", line 73, in Reformat
        verifier.VerifyCode(formatted_code[-1])
      File "/home/david/yapf/yapf/yapflib/verifier.py", line 45, in VerifyCode
        compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
      File "<string>", line 2
        @foo
           ^
    SyntaxError: invalid syntax

**Comment by DRMacIver** [comment]
Confirmed in master.
