### ISSUE TITLE
Closing bracket can be lined up with the wrong opening bracket

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#30]
This produces the same pep error as #26 but I think is not the same bug. Obviously feel free to close it as a duplicate if I'm wrong.

The following code:

    class A(object):

        def f(self, aaaaaaaaa, bbbbbbbbbbbbb, row):
            if True:
                if row[4] is None or row[5] is None:
                    bbbbbbbbbbbbb['..............'] = row[
                        5] if row[5] is not None else 5

is reformatted by yapf --style=pep8 as

    class A(object):
        def f(self, aaaaaaaaa, bbbbbbbbbbbbb, row):
            if True:
                if row[4] is None or row[5] is None:
                    bbbbbbbbbbbbb['..............'] = row[5] if row[5
                                 ] is not None else 5

Note that the closing bracket on the following line is being lined up with the opening bracket from an entirely different indexing expression. This is both a pep8 violation and also rather misleading.

**Comment by jason-kane** [comment]
Umm, same input file w/fresh pull of yapf.  Disturbing results:

$ cat test.py
```python
class A(object):

    def f(self, aaaaaaaaa, bbbbbbbbbbbbb, row):
        if True:
            if row[4] is None or row[5] is None:
                bbbbbbbbbbbbb['..............'] = row[
                    5] if row[5] is not None else 5
```

$ yapf --style=pep8 test.py
```python
class A(object):
    def f(self, aaaaaaaaa, bbbbbbbbbbbbb, row):
        if True:
            if row[4] is None or row[5] is None:
                bbbbbbbbbbbbb['..............']=row[5]ifrow[5]isnotNoneelse5
```

$ yapf --verify --style=pep8 test.py
```python
Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 9, in <module>
    load_entry_point('yapf==0.1.9', 'console_scripts', 'yapf')()
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/__init__.py", line 223, in run_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/__init__.py", line 153, in main
    verify=args.verify)
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/__init__.py", line 187, in FormatFiles
    print_diff=print_diff, verify=verify)
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/yapflib/yapf_api.py", line 79, in FormatFile
    verify=verify), encoding
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/yapflib/yapf_api.py", line 118, in FormatCode
    reformatted_source = reformatter.Reformat(uwlines, verify)
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/yapflib/reformatter.py", line 107, in Reformat
    verifier.VerifyCode(formatted_code[-1])
  File "/usr/local/lib/python2.7/dist-packages/yapf-0.1.9-py2.7.egg/yapf/yapflib/verifier.py", line 52, in VerifyCode
    raise InternalError(sys.exc_info()[1])
yapf.yapflib.verifier.InternalError: invalid syntax (<string>, line 1)
```

As you can see from the traceback, python 2.7, yapf 0.1.9.  The yapf is bleeding edge master (as of a couple minutes ago).

**Comment by gwelymernans** [comment]
Ye gads! That sucks. I added a quick fix for this. But it need to be revisited in the future.
