### ISSUE TITLE
lib2to3 parse error on well formed code that 2to3 passes fine

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#32]
The following code:

    def response(                  using=None):
        if (context_instance is _context_instance_undefined and
            dirs is _dirs_undefined and dictionary is _dictionary_undefined):
                return to

Gives me the following exception when run under python 3.4:

    Traceback (most recent call last):
      File "/home/david/yapf/yapf/yapflib/pytree_utils.py", line 85, in ParseCodeToTree
        tree = parser_driver.parse_string(code, debug=False)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
        return self.parse_tokens(tokens, debug)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
        if p.addtoken(type, value, (prefix, start)):
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/parse.py", line 159, in addtoken
        raise ParseError("bad input", type, value, context)
    lib2to3.pgen2.parse.ParseError: bad input: type=6, value='', context=('\n', (5, 0))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/david/yapf/yapf/__main__.py", line 18, in <module>
        sys.exit(yapf.main(sys.argv))
      File "/home/david/yapf/yapf/__init__.py", line 102, in main
        print_diff=args.diff)
      File "/home/david/yapf/yapf/__init__.py", line 124, in FormatFiles
        filename, style_config=style_config, lines=lines, print_diff=print_diff)
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 67, in FormatFile
        print_diff=print_diff)
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 88, in FormatCode
        tree = pytree_utils.ParseCodeToTree(unformatted_source)
      File "/home/david/yapf/yapf/yapflib/pytree_utils.py", line 91, in ParseCodeToTree
        tree = parser_driver.parse_string(code, debug=False)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
        return self.parse_tokens(tokens, debug)
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
        if p.addtoken(type, value, (prefix, start)):
      File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/parse.py", line 159, in addtoken
        raise ParseError("bad input", type, value, context)
    lib2to3.pgen2.parse.ParseError: bad input: type=6, value='', context=('\n', (5, 0))

Running the normal 2to3 command line utility on this file works fine, so I think there's something about what you're passing in to 2to3.

**Comment by DRMacIver** [comment]
And here's an ill formed example that generates a similar exception. I leave it as an exercise for the amused reader to figure out how I accidentally hit upon this one:

    echo 'from . import foo'

(Yes, you put that code in a python file)

**Comment by DRMacIver** [comment]
Ah! I understand what's going on now.

You will get this error if you try to format a file where the last character of the file is not whitespace. This will probably mean that you can't reproduce any of the above by copying and pasting them.

**Comment by gwelymernans** [comment]
Yeah. lib2to3 is sensitive like that. I could enforce a newline at the end of the source code. That might work?

**Comment by DRMacIver** [comment]
Sounds good to me. Normalising end of file whitespace is something I'd want out of a code formatter anyway.

**Comment by gwelymernans** [comment]
Fixed here: c80d69c
