### ISSUE TITLE
PEP 515 Not Supported (Underscores in Numeric Literals)

### ISSUE THREAD

**Issue by omidmnz** [google/yapf#370]
Yapf 0.16.0 crashes on the following input (which is valid python code according to [PEP 515](https://www.python.org/dev/peps/pep-0515/)):
```python
million = 1000_000
```
raising this exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 102, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='_000', context=('', (1, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yapf", line 11, in <module>
    load_entry_point('yapf==0.16.0', 'console_scripts', 'yapf')()
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 296, in run_main
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 188, in main
    parallel=args.parallel)
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 236, in FormatFiles
    in_place, print_diff, verify)
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 259, in _FormatFile
    logger=logging.warning)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 126, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 108, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='_000', context=('', (1, 14))

```
But it works as expected on the following code:
```python
million = 1000000
```

**Comment by nevsan** [comment]
I looked into this a little bit. It seems that the problem is not with `YAPF` but with `lib2to3`. Particularly, the tokenizer doesn't include underscores in its regular expressions for numbers (see [here](https://github.com/python/cpython/blob/master/Lib/lib2to3/pgen2/tokenize.py#L57-L60)).

Because the regular expressions are compiled at the time `lib2to3.pgen2.tokenize` is imported (and because these number show up in many other compiled expressions), I don't see a clean way to monkey patch this. I've gotten it to work with this added to `pytree_utils.py`:
```python
# In Python 3.6, you can have underscores in numeric literals--lib2to3 seems to have overlooked.
# Unfortunately, a lot of work has to be done to really take care of this.
tokenize.Binnumber = r'0[bB][01_]*'
tokenize.Hexnumber = r'0[xX][\da-fA-F_]*[lL]?'
tokenize.Octnumber = r'0[oO]?[0-7_]*[lL]?'
tokenize.Decnumber = r'[1-9][\d_]*[lL]?'
tokenize.Intnumber = tokenize.group(tokenize.Binnumber, tokenize.Hexnumber, tokenize.Octnumber, tokenize.Decnumber)
tokenize.Number = tokenize.group(tokenize.Imagnumber,
                                 tokenize.Floatnumber,
                                 tokenize.Intnumber)
tokenize.PlainToken = tokenize.group(tokenize.Number, tokenize.Funny, tokenize.String, tokenize.Name)
tokenize.Token = tokenize.Ignore + tokenize.PlainToken

tokenize.PseudoToken = tokenize.Whitespace + tokenize.group(tokenize.PseudoExtras, tokenize.Number, tokenize.Funny, tokenize.ContStr, tokenize.Name)
tokenize.tokenprog, tokenize.pseudoprog = list(map(re.compile, (tokenize.Token, tokenize.PseudoToken)))
```
But it seems fragile. I'll leave it up to maintainers whether to include a dirty patch like this, or wait for an upstream fix in Python 3.6.

**Comment by nevsan** [comment]
See https://github.com/python/cpython/pull/752. We'll see where this goes.

**Comment by Alok** [comment]
[That PR](https://github.com/python/cpython/pull/752) was merged in to lib2to3, but I still get this error with `yapf 0.16.2`.

On a side note, I *think* [jedi](https://github.com/python/cpython/pull/752) has their own parser, which may work as a replacement for the one currently used.

**Comment by nevsan** [comment]
It was merged, but unfortunately the official Python 3.6.2 release isn't expected until late June. If you really need, you could find a way to monkey patch the regexes in the mean time, but it's not exactly straightforward.
