### ISSUE TITLE
lib2to3 error if code contains {**a_dict}

### ISSUE THREAD

**Issue by takeontom** [google/yapf#402]
Have found YAPF is erroring out if the code contains the `{**a_dict}` method of copying a dict.

Example code which triggers the error:

```python
a_dict = {'key': 'value'}
a_dict_copy = {**a_dict}
print('a_dict:', a_dict)
print('a_dict_copy:', a_dict_copy)
```

I note this line in the README:

> YAPF requires the code it formats to be valid Python for the version YAPF itself runs under. Therefore, if you format Python 3 code with YAPF, run YAPF itself under Python 3 (and similarly for Python 2).

The `{**a_dict}` syntax is only valid in Python3 - but it's failing in a Python3.5 virtualenv:

```shell
$ python --version
Python 3.5.2
$ which python
/home/tom/.virtualenvs/yapfexample/bin/python
$ yapf --version
yapf 0.16.1
$ which yapf
/home/tom/.virtualenvs/yapfexample/bin/yapf
```

The Python code is OK:

```shell
$ python example-yapf-fail.py 
a_dict: {'key': 'value'}
a_dict_copy: {'key': 'value'}
```

And the error from YAPF:

```shell
$ yapf example-yapf-fail.py 
Traceback (most recent call last):
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 102, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=36, value='**', context=('', (2, 15))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.virtualenvs/yapfexample/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/__init__.py", line 296, in run_main
    sys.exit(main(sys.argv))
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/__init__.py", line 188, in main
    parallel=args.parallel)
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/__init__.py", line 236, in FormatFiles
    in_place, print_diff, verify)
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/__init__.py", line 259, in _FormatFile
    logger=logging.warning)
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 126, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/tom/.virtualenvs/yapfexample/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 108, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=36, value='**', context=('', (2, 15))
```

**Comment by jack17529** [comment]
Maybe I can help.

**Comment by gwelymernans** [comment]
If you could, I would really appreciate it. :-)

**Comment by bastih** [comment]
This can be fixed by updating to python 3.6 - lib2to3 in python 3.5 lacks the correct means to parse the splat (`**`) operator.
