### ISSUE TITLE
yapf cannot handle 3.x metaclass syntax when run under 2.7

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#42]
The following code will produce an internal error when yapf is run under 2.7:

    class ABC(metaclass=type):
        pass

The error is:

    INTERNAL ERROR: class ABC(metaclass=type):
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/david/yapf/yapf/__main__.py", line 18, in <module>
        sys.exit(yapf.main(sys.argv))
      File "/home/david/yapf/yapf/__init__.py", line 102, in main
        print_diff=args.diff)
      File "/home/david/yapf/yapf/__init__.py", line 124, in FormatFiles
        filename, style_config=style_config, lines=lines, print_diff=print_diff)
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 67, in FormatFile
        print_diff=print_diff)
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 110, in FormatCode
        reformatted_source = reformatter.Reformat(uwlines)
      File "/home/david/yapf/yapf/yapflib/reformatter.py", line 73, in Reformat
        verifier.VerifyCode(formatted_code[-1])
      File "/home/david/yapf/yapf/yapflib/verifier.py", line 45, in VerifyCode
        compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
      File "<string>", line 1
        class ABC(metaclass=type):
                           ^
    SyntaxError: invalid syntax

**Comment by eliben** [comment]
To format Python 3 code, run yapf under Python 2, and vice versa. This is because yapf tries to verify it didn't mess up the semantic meaning of the code. The sample you pasted is invalid in Python 2

**Comment by DRMacIver** [comment]
I don't think the way this is currently handled is a good call. It's fine (well, not fine, but acceptable) if yapf can't format code running on a different version, but crashing is a really bad way to signal this and severely limits the utility. If you can't parse code as valid python syntax when you're given it, silently doing nothing (or better yet, giving a warning) is better than crashing.

One of the problems here is that code bases for libraries can be and often are mixed python 2 / python 3. I'd *love* to be able to drop python 2 support, but I basically can't, and until the point when I can the entire code base is highly likely to have some bits which don't parse correctly on python 2 and some bits that don't parse correctly on python 3 (as it happens I've avoided this so far, but I'm not going to be able to for much longer), so unless I'm very very careful about how I run yapf it's just going to crash.
