### ISSUE TITLE
python 3.6 f-string format

### ISSUE THREAD

**Issue by garrettheel** [google/yapf#451]
It seems that f-strings are not understood correctly by the formatter. Whilst upgrading to python3.6.2 did stop yapf barfing on them altogether, the behavior is still weird.

E.g
```
     def something(self) -> Dict[str, str]:
         return {
-            'a': f'{b}'
+            'a':
+            f'{b}'
         }
```

**Comment by sschaetz** [comment]
Can reproduce with 0.16.0 (Python 3.6.1). 

Reproducer:

```
v = 4
x = (f'{v}')
print(x)
```

Error:
```
Traceback (most recent call last):
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/__init__.py", line 296, in run_main
    sys.exit(main(sys.argv))
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/__init__.py", line 188, in main
    parallel=args.parallel)
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/__init__.py", line 236, in FormatFiles
    in_place, print_diff, verify)
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/__init__.py", line 259, in _FormatFile
    logger=logging.warning)
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 126, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Users/sschaetz/.pyenv/versions/software-3.6.1/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 108, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Users/sschaetz/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Users/sschaetz/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Users/sschaetz/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'{v}'", context=('', (2, 6))
```

**Comment by gwelymernans** [comment]
Yeah. I've been playing around trying to switch to [awpa](https://github.com/pyga/awpa). I haven't had many cycles to work on it. I'd love it if someone could help out with it! ;-)

**Comment by ipfans** [comment]
@gwelymernans how can we help?

**Comment by ipfans** [comment]
@gwelymernans what should we do for contribution?

**Comment by gwelymernans** [comment]
@ipfans If you're willing to contribute, I would love it! :-) All you would need to do is get YAPF working with awpa. There is a contributor's licensing agreement to sign, but that can be taken care of once you have a PR ready.

**Comment by LuRsT** [comment]
Is there any workaround for this issue? Even if that means commenting the line for yapf to ignore?

**Comment by pappasam** [comment]
I'm running yapf version 0.25 and Python 3.7.1; this issue seems to be resolved in that environment.

**Comment by tvykruta** [comment]
We're having the same problem. fstrings are not working in python 3.74 yapf 0.28.0 from command line:

```
(venv) Tomass-MacBook-Pro:data-pipeline tv$ yapf --version
yapf 0.28.0
(venv) Tomass-MacBook-Pro:data-pipeline tv$ python --version
Python 3.7.4
(venv) Tomass-MacBook-Pro:data-pipeline tv$ yapf fstrings_test.py 
Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 10, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 335, in run_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 220, in main
    verbose=args.verbose)
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 270, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 296, in _FormatFile
    logger=logging.warning)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 91, in FormatFile
    verify=verify)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 129, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "fstrings_test.py", line 3
    print(f"He said his name is {name}.")
                                       ^
SyntaxError: invalid syntax
```
Test file:
```
(venv) Tomass-MacBook-Pro:data-pipeline tv$ more fstrings_test.py 
name      = "Fred"
print("He said his name is {}" % name)
print(f"He said his name is {name}.")


```

Running FormatCode directly works:

```
(venv) Tomass-MacBook-Pro:data-pipeline tv$ python fstring_test2.py 
('f"test"\n', False)
(venv) Tomass-MacBook-Pro:data-pipeline tv$ cat fstring_test2.py 
from yapf.yapflib.yapf_api import FormatCode
p = FormatCode('f"test"')
print(p)
(venv) Tomass-MacBook-Pro:data-pipeline tv$ 
```

**Comment by bwendling** [comment]
Closed with 7c408b9d7750292760ed255f744211d1ef535668
