### ISSUE TITLE
Another lib2to3 parse error

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#46]
This one is not caused by whitespace as far as I can tell, or at least not at the end of the file:

    def walk(top, topdown=True, onerror=None, followlinks=False):
                yield from walk(new_path, topdown, onerror, followlinks)

Produces the error:

    Traceback (most recent call last):
      File "/home/david/yapf/yapf/yapflib/pytree_utils.py", line 85, in ParseCodeToTree
        tree = parser_driver.parse_string(code, debug=False)
      File "/usr/lib/python3.2/lib2to3/pgen2/driver.py", line 106, in parse_string
        return self.parse_tokens(tokens, debug)
      File "/usr/lib/python3.2/lib2to3/pgen2/driver.py", line 71, in parse_tokens
        if p.addtoken(type, value, (prefix, start)):
      File "/usr/lib/python3.2/lib2to3/pgen2/parse.py", line 159, in addtoken
        raise ParseError("bad input", type, value, context)
    lib2to3.pgen2.parse.ParseError: bad input: type=5, value='    ', context=('', (1, 0))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.2/runpy.py", line 160, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python3.2/runpy.py", line 73, in _run_code
        exec(code, run_globals)
      File "/home/david/yapf/yapf/__main__.py", line 18, in <module>
        sys.exit(yapf.main(sys.argv))
      File "/home/david/yapf/yapf/__init__.py", line 98, in main
        lines=lines))
      File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 88, in FormatCode
        tree = pytree_utils.ParseCodeToTree(unformatted_source.rstrip() + '\n')
      File "/home/david/yapf/yapf/yapflib/pytree_utils.py", line 91, in ParseCodeToTree
        tree = parser_driver.parse_string(code, debug=False)
      File "/usr/lib/python3.2/lib2to3/pgen2/driver.py", line 106, in parse_string
        return self.parse_tokens(tokens, debug)
      File "/usr/lib/python3.2/lib2to3/pgen2/driver.py", line 71, in parse_tokens
        if p.addtoken(type, value, (prefix, start)):
      File "/usr/lib/python3.2/lib2to3/pgen2/parse.py", line 159, in addtoken
        raise ParseError("bad input", type, value, context)
    lib2to3.pgen2.parse.ParseError: bad input: type=5, value='    ', context=('', (1, 0))

**Comment by gwelymernans** [comment]
It's chocking on the "yield from ..." syntax. I assume that this is Python 3.x? I get the same when I run '2to3' on it:

```
[morbo:yapf] 2to3 /tmp/bad.py
RefactoringTool: Skipping implicit fixer: buffer
RefactoringTool: Skipping implicit fixer: idioms
RefactoringTool: Skipping implicit fixer: set_literal
RefactoringTool: Skipping implicit fixer: ws_comma
RefactoringTool: Can't parse /tmp/bad.py: ParseError: bad input: type=1, value=u'from', context=(u' ', (2, 18))
RefactoringTool: No files need to be modified.
RefactoringTool: There was 1 error:
RefactoringTool: Can't parse /tmp/bad.py: ParseError: bad input: type=1, value=u'from', context=(u' ', (2, 18))
```

**Comment by myint** [comment]
I might be wrong, but wasn't `yield from` introduced in [3.3](https://docs.python.org/dev/whatsnew/3.3.html#pep-380-syntax-for-delegating-to-a-subgenerator) and not `3.2`, which @DRMacIver seems to be using?

**Comment by DRMacIver** [comment]
I am indeed using 3.2 for running this, mostly due to a quirk of my system setup. I'll try to only report things that happen on 3.4 in future. Sorry for the confusion.

**Comment by DRMacIver** [comment]
I see you don't in fact support 3.2, so I will close this as invalid.
