### ISSUE TITLE
yapf will crash if you run it on a file with a byte order mark

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#50]
In the interests of not having github eat the important details, here is an example file encoded as a python string literal:

    "\ufeff# -*- coding: utf-8 -*-\n\nresult = 'passed'\n"

(Yes, I know that a bom in a utf-8 file doesn't make sense. Don't ask me, I just find 'em).

Running on python 3.4.2 with the latest master this will produce the following lib2to3 error:

        Traceback (most recent call last):
          File "/home/david/yapf/yapf/yapflib/pytree_utils.py", line 85, in ParseCodeToTree
            tree = parser_driver.parse_string(code, debug=False)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
            return self.parse_tokens(tokens, debug)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
            if p.addtoken(type, value, (prefix, start)):
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/parse.py", line 116, in addtoken
            ilabel = self.classify(type, value, context)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/parse.py", line 172, in classify
            raise ParseError("bad token", type, value, context)
        lib2to3.pgen2.parse.ParseError: bad token: type=56, value='\ufeff', context=('', (1, 0))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/runpy.py", line 170, in _run_module_as_main
            "__main__", mod_spec)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/runpy.py", line 85, in _run_code
            exec(code, run_globals)
          File "/home/david/yapf/yapf/__main__.py", line 18, in <module>
            sys.exit(yapf.main(sys.argv))
          File "/home/david/yapf/yapf/__init__.py", line 102, in main
            print_diff=args.diff)
          File "/home/david/yapf/yapf/__init__.py", line 124, in FormatFiles
            filename, style_config=style_config, lines=lines, print_diff=print_diff)
          File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 67, in FormatFile
            print_diff=print_diff)
          File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 88, in FormatCode
            tree = pytree_utils.ParseCodeToTree(unformatted_source.rstrip() + '\n')
          File "/home/david/yapf/yapf/yapflib/pytree_utils.py", line 91, in ParseCodeToTree
            tree = parser_driver.parse_string(code, debug=False)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 106, in parse_string
            return self.parse_tokens(tokens, debug)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/driver.py", line 71, in parse_tokens
            if p.addtoken(type, value, (prefix, start)):
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/parse.py", line 116, in addtoken
            ilabel = self.classify(type, value, context)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/lib2to3/pgen2/parse.py", line 172, in classify
            raise ParseError("bad token", type, value, context)
        lib2to3.pgen2.parse.ParseError: bad token: type=56, value='\ufeff', context=('', (1, 0))

Running 2to3 itself on the file works correctly.

**Comment by wkschwartz** [comment]
For what it's worth, the encoding declaration in the example file isn't quite correct. Python calls utf-8 with BOM [`utf-8-sig`](https://docs.python.org/3/library/codecs.html#module-encodings.utf_8_sig).

**Comment by gwelymernans** [comment]
If I open the file in a similar way to how `lib2to3` is opening it, then it processes the file just fine. However, it doesn't retain the BOM, which I assume is a bit of a problem?

**Comment by wkschwartz** [comment]
The `utf-8-sig` codec skips the BOM when it's the start of the file
