### ISSUE TITLE
chokes on `with (yield from ...)` syntax

### ISSUE THREAD

**Issue by jab** [google/yapf#55]
yapf chokes with `SyntaxError: unexpected EOF while parsing` on input like the following:
```python
from asyncio import coroutine, Lock
lock = Lock()
@coroutine
def foo():
    with (yield from lock):
        return 42
```
See https://gist.github.com/jab/8df5bfae6ba13c0d51d5.

This syntax is given as an example in https://docs.python.org/dev/library/asyncio-sync.html#lock (search for "Context manager usage:").

**Comment by gwelymernans** [comment]
This was reported in #46.

**Comment by jab** [comment]
Didn't see that, looks like because #46 was closed 3 days ago as invalid. Confused by giving this the "duplicate" label while leaving it open. Do you intend to fix?

**Comment by myint** [comment]
@jab seems to be using Python 3.4 so I think this is a different issue from #46.

**Comment by jab** [comment]
Thanks @myint, yes, I meant to say that too, I am using Python 3.4.

**Comment by eliben** [comment]
@jab can you try to rerun it in `master` -- I wonder what you'd get now that we disabled verification?

I'm actually getting 

           raise ParseError("bad input", type, value, context)
      lib2to3.pgen2.parse.ParseError: bad input: type=1, value='from', context=(' ', (5, 16))

When running this with Python 3.4.0; I'm surprised that you're not seeing it as well

**Comment by jab** [comment]
@eliben The `../../tmp/yapf` directory referenced in the gist I linked above was already running off a recent revision of master (f5e50b6ec9706ac793e044ce1cc8aeacab84c547) though a few revisions behind current latest. I updated to current latest and am still reproducing with Python 3.4.3:

```
bash-4.3$ pwd
/Users/jab/tmp/yapf
bash-4.3$ git rev-parse HEAD
f5e50b6ec9706ac793e044ce1cc8aeacab84c547
bash-4.3$ git pull
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 35 (delta 28), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (35/35), done.
From https://github.com/google/yapf
   f5e50b6..7a01d00  master     -> origin/master
Updating f5e50b6..7a01d00
Fast-forward
 README.rst                      | 83 +++++++++++++++++++++++++++++++----------
 yapf/__init__.py                |  8 ++--
 yapf/yapflib/split_penalty.py   | 36 ++++++++++++------
 yapf/yapflib/style.py           |  5 +++
 yapf/yapflib/unwrapped_line.py  |  4 +-
 yapf/yapflib/verifier.py        |  8 ++--
 yapftests/reformatter_test.py   | 29 ++++++++++++--
 yapftests/split_penalty_test.py | 21 ++++++-----
 yapftests/yapf_test.py          |  4 +-
 9 files changed, 145 insertions(+), 53 deletions(-)
bash-4.3$ echo 'from asyncio import coroutine, Lock
> lock = Lock()
> @coroutine
> def foo():
>     with (yield from lock):
>         return 42' > /tmp/foo.py
bash-4.3$ cat /tmp/foo.py
from asyncio import coroutine, Lock
lock = Lock()
@coroutine
def foo():
    with (yield from lock):
        return 42
bash-4.3$ python3 --version
Python 3.4.3
bash-4.3$ python3 yapf /tmp/foo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/yapf/yapflib/verifier.py", line 41, in VerifyCode
    compile(textwrap.dedent(code).encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 2
    with (yield from lock):
                          ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/yapf/yapflib/verifier.py", line 44, in VerifyCode
    ast.parse(textwrap.dedent(code.lstrip('\n')).lstrip(), '<string>', 'exec')
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<string>", line 1
    with (yield from lock):
                          ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "yapf/__main__.py", line 18, in <module>
    sys.exit(yapf.main(sys.argv))
  File "/usr/local/lib/python3.4/site-packages/yapf/__init__.py", line 109, in main
    print_diff=args.diff, verify=not args.noverify)
  File "/usr/local/lib/python3.4/site-packages/yapf/__init__.py", line 133, in FormatFiles
    print_diff=print_diff, verify=verify)
  File "/usr/local/lib/python3.4/site-packages/yapf/yapflib/yapf_api.py", line 72, in FormatFile
    verify=verify)
  File "/usr/local/lib/python3.4/site-packages/yapf/yapflib/yapf_api.py", line 118, in FormatCode
    reformatted_source = reformatter.Reformat(uwlines, verify)
  File "/usr/local/lib/python3.4/site-packages/yapf/yapflib/reformatter.py", line 75, in Reformat
    verifier.VerifyCode(formatted_code[-1])
  File "/usr/local/lib/python3.4/site-packages/yapf/yapflib/verifier.py", line 48, in VerifyCode
    compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 1
SyntaxError: 'yield' outside function
```

**Comment by jab** [comment]
Sorry, just noticed my environment was using an older version of yapf installed in /usr/local! Reran `python setup.py install` from latest master and now no longer get an error:
```
bash-4.3$ python3 yapf /tmp/foo.py
from asyncio import coroutine, Lock
lock = Lock()


@coroutine
def foo():
    with (yield from lock):
        return 42
```
Has this been fixed in latest?

**Comment by gwelymernans** [comment]
Sorry about leaving this open. I was hoping that others would comment just in case it wasn't a real duplicate (this is an area of Python that I'm less good at). But if it works for you now then great! :-)

**Comment by jab** [comment]
@gwelymernans It still doesn't work if `--verify` is passed though. (Fails with:
```
with (yield from lock):
                              ^
SyntaxError: unexpected EOF while parsing
```
)
Is it intended to?

**Comment by gwelymernans** [comment]
Technically it should work, but we're now discouraging people from using the `--verify` flag. It leads to situations like this, where the formatted code is fine by it still generates an error. So don't worry about it. :-)

**Comment by eliben** [comment]
I think closing this issue is the right decision

This seems to work alright in Python 3.4

As for verification, this is not currently recommended for end users - we use it internally for development and testing.
