### ISSUE TITLE
Keyword expansion within dict caused yapf crash

### ISSUE THREAD

**Issue by brendanator** [google/yapf#562]
Running yapf on 
```python
dict1 = {1:2}
dict2 = {**dict1}
```
which is valid syntax added in [PEP 448](https://www.python.org/dev/peps/pep-0448/) throws an exception
```
Traceback (most recent call last):
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 103, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=36, value='**', context=('', (2, 9))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 128, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 109, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=36, value='**', context=('', (2, 9))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/__init__.py", line 312, in run_main
    sys.exit(main(sys.argv))
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/__init__.py", line 200, in main
    verbose=args.verbose)
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/__init__.py", line 250, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/__init__.py", line 275, in _FormatFile
    logger=logging.warning)
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/home/brendan/.local/share/virtualenvs/jobwarrior--e6pxd6u/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 130, in FormatCode
    raise parse.ParseError(filename + ': ' + e.message)
AttributeError: 'ParseError' object has no attribute 'message'
```

**Comment by gwelymernans** [comment]
This looks like a lib2to3 error. What python version are you using?

**Comment by brendanator** [comment]
Python 3.5

**Comment by gwelymernans** [comment]
You need to use Python 3.6 for it to work. The lib2to3 bug is fixed in that version.

**Comment by brendanator** [comment]
@gwelymernans This isn't always an option if yapf is installed through pipenv as a dev dependency in a python3.5 environment

Anyway, I can just upgrade. Thanks
