### ISSUE TITLE
Dictionary extend with ** fails

### ISSUE THREAD

**Issue by lerrigatto** [google/yapf#594]
Reproduce with:

```
cat repro.py
var = {**a, **b}
```
Yelds:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yapf/yapflib/pytree_utils.py", line 102, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=36, value='**', context=('', (1, 7))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.5/dist-packages/yapf/__init__.py", line 296, in run_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.5/dist-packages/yapf/__init__.py", line 188, in main
    parallel=args.parallel)
  File "/usr/local/lib/python3.5/dist-packages/yapf/__init__.py", line 236, in FormatFiles
    in_place, print_diff, verify)
  File "/usr/local/lib/python3.5/dist-packages/yapf/__init__.py", line 259, in _FormatFile
    logger=logging.warning)
  File "/usr/local/lib/python3.5/dist-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/usr/local/lib/python3.5/dist-packages/yapf/yapflib/yapf_api.py", line 126, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python3.5/dist-packages/yapf/yapflib/pytree_utils.py", line 108, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=36, value='**', context=('', (1, 7))
```

**Comment by kamahen** [comment]
This seems to be a problem with running yapf under Python 3.5 ... if I
change to Python 3.6 or 3.7, it works.

(But the syntax seems to be valid with Python 3.5, so perhaps the packaging
of yapf somehow causes it to pick up a wrong version of Lib/lib2to3?)

**Comment by cybojenix** [comment]
For those that stumble upon this issue, the missing functionality in `lib2to3` was added in python 3.5.3, so updating to that version or later will resolve the error for you.


https://github.com/python/cpython/commit/28325749c01815097aa2bc06508004a1f894c279
