### ISSUE TITLE
SyntaxError for 'async def'

### ISSUE THREAD

**Issue by idodin** [google/yapf#597]
Hi there!

We're getting an error when attempting to run `yapf --recursive .` on our source code. A SyntaxError is raised when formatting our Main.py which looks like this:
```python
#!/usr/bin/env python3

# discord-py requirements
import asyncio
import discord
from discord.ext import commands
import asyncio

# for database
import sqlite3

# logger
import logging

# Other utilities
import os
import sys
from config import parser
import random

# List the extensions (modules) that should be loaded on startup.
startup = [
    "cogs.reminder",
    "cogs.memes",
    "cogs.helpers",
    "cogs.mod",
    "cogs.score",
    "cogs.quotes"
]

bot = commands.Bot(command_prefix='?')

# Logging configuration
logger = logging.getLogger('discord')
logger.setLevel(logging.ERROR)
handler = logging.FileHandler(
    filename='discord.log', encoding='utf-8', mode='w')
handler.setFormatter(
    logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)


@bot.event
async def on_ready():
    print('Logged in as {0} ({1})'.format(bot.user.name, bot.user.id))


@bot.command()
@commands.has_role("Discord Moderator")
async def load(ctx, extension_name: str):
    '''
    Load a specific extension.
    '''
    try:
        bot.load_extension(extension_name)
    except (AttributeError, ImportError) as e:
        await ctx.send("```{}: {}\n```".format(type(e).__name__, str(e)))

        return
    await ctx.send("{} loaded.".format(extension_name))


@bot.command()
@commands.has_role("Discord Moderator")
async def unload(ctx, extension_name: str):
    '''
    Unload a specific extension.
    '''
    bot.unload_extension(extension_name)
    await ctx.send("Unloaded {}.".format(extension_name))


@bot.command()
@commands.has_role("Discord Moderator")
async def restart(ctx):
    '''
    Restart the bot
    '''
    await ctx.send('https://streamable.com/dli1')
    python = sys.executable
    os.execl(python, python, *sys.argv)


@bot.command()
@commands.has_role("Discord Moderator")
async def sleep(ctx):
    '''
    Shut down the bot
    '''
    await ctx.send('Bye')
    await bot.logout()
    print('Bot shut down')


@bot.command()
async def update(ctx):
    '''
    Update the bot by pulling changes from the git repository
    '''
    await ctx.send('https://streamable.com/c7s2o')
    os.system('git pull')


@bot.event
async def on_message(message):
    if message.author == bot.user:
        return
    if message.content == "dammit marty":
        await message.channel.send(":c")
    if message.content == "worm":
        await message.channel.send(
            "walk without rhythm, and it won't attract the worm.")
    if message.content == "hey":
        await message.channel.send("whats going on?")
    await bot.process_commands(message)


@bot.event
async def on_member_join(member):
    channel = bot.get_channel(236668784948019202)
    welcome_message = random.choice(bot.config.welcome).format(member.mention)
    message = await channel.send(welcome_message)
    await message.add_reaction(":suzeping:457285258682040329")


@bot.event
async def on_member_remove(member):
    channel = bot.get_channel(236668784948019202)
    goodbye_message = random.choice(bot.config.goodbye).format(member.mention)
    message = await channel.send(goodbye_message)
    await message.add_reaction(":biblethump:243942559360090132")


# Startup extensions
# If statement will only execute if we are running this file (i.e. won't run
# if it's imported)
if __name__ == "__main__":
    bot.config = parser.Parser()
    conn = sqlite3.connect(bot.config.db_path)
    c = conn.cursor()
    with open('./Martlet.schema') as fp:
        c.executescript(fp.read())
        conn.commit()
        conn.close()
    for extension in startup:
        try:
            bot.load_extension(extension)
        except Exception as e:
            print('Failed to load extension {}\n{}: {}'.format(
                extension,
                type(e).__name__, e))
    bot.run(bot.config.discord_key)

```

The error returned looks like this:

```
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\yapf\yapflib\pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "c:\python34\lib\lib2to3\pgen2\driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "c:\python34\lib\lib2to3\pgen2\driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "c:\python34\lib\lib2to3\pgen2\parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='async', context=('', (44, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\yapf\yapflib\pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "c:\python34\lib\lib2to3\pgen2\driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "c:\python34\lib\lib2to3\pgen2\driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "c:\python34\lib\lib2to3\pgen2\parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='async', context=('', (44, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\yapf.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\yapf\__init__.py", line 313, in run_main
    sys.exit(main(sys.argv))
  File "c:\python34\lib\site-packages\yapf\__init__.py", line 201, in main
    verbose=args.verbose)
  File "c:\python34\lib\site-packages\yapf\__init__.py", line 251, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "c:\python34\lib\site-packages\yapf\__init__.py", line 276, in _FormatFile
    logger=logging.warning)
  File "c:\python34\lib\site-packages\yapf\yapflib\yapf_api.py", line 91, in FormatFile
    verify=verify)
  File "c:\python34\lib\site-packages\yapf\yapflib\yapf_api.py", line 129, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "c:\python34\lib\site-packages\yapf\yapflib\pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "c:\python34\lib\site-packages\yapf\yapflib\pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "c:\python34\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File ".\Main.py", line 44
    async def on_ready():
        ^
SyntaxError: invalid syntax
```

I came across #353 , however our code does not seem to be malformed and so we are at a loss. 

Could this be an error related to the use of the `discord-py` library which handles the asyncio event loop for us? i.e. being raised because co-routines are defined but no event loop is found in our source code? 

We are running on Python 3.6 which support use of the `async` keyword. 

Thanks!

**Comment by kamahen** [comment]
This is the same cause as Issue #586

**Comment by idodin** [comment]
@kamahen Thank you! Sorry, must have missed that issue. Will close this now!
