### ISSUE TITLE
yapf gbk file does not work bug?

### ISSUE THREAD

**Issue by whiteWords** [google/yapf#604]
D:>yapf d:\测试\a.py
Traceback (most recent call last):
File "c:\python27\lib\runpy.py", line 174, in run_module_as_main
"main", fname, loader, pkg_name)
File "c:\python27\lib\runpy.py", line 72, in run_code
exec code in run_globals
File "C:\Python27\Scripts\yapf.exe_main.py", line 9, in 
File "c:\python27\lib\site-packages\yapf_init.py", line 313, in run_main
sys.exit(main(sys.argv))
File "c:\python27\lib\site-packages\yapf_init_.py", line 201, in main
verbose=args.verbose)
File "c:\python27\lib\site-packages\yapf_init_.py", line 251, in FormatFiles
in_place, print_diff, verify, verbose)
File "c:\python27\lib\site-packages\yapf_init_.py", line 276, in _FormatFile
logger=logging.warning)
File "c:\python27\lib\site-packages\yapf\yapflib\yapf_api.py", line 91, in FormatFile
verify=verify)
File "c:\python27\lib\site-packages\yapf\yapflib\yapf_api.py", line 154, in FormatCode
unformatted_source, reformatted_source, filename=filename)
File "c:\python27\lib\site-packages\yapf\yapflib\yapf_api.py", line 291, in _GetUnifiedDiff
lineterm='')) + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 7: ordinal not in range(128)

D:>yapf a.py
a = 1
b = 2
c = 3

yapf‘s bug?

**Comment by whiteWords** [comment]
ping @gwelymernans @CardenB

**Comment by gwelymernans** [comment]
I'm not able to replicate this error. Is it a Windows issue?

**Comment by whiteWords** [comment]
Microsoft Windows [版本 10.0.17134.228]

**Comment by whiteWords** [comment]
difflib.unified_diff bug?

**Comment by whiteWords** [comment]
Python 2.7.15

debug:

def _GetUnifiedDiff(before, after, filename='code'):
  """Get a unified diff of the changes.

  Arguments:
    before: (unicode) The original source code.
    after: (unicode) The reformatted source code.
    filename: (unicode) The code's filename.

  Returns:
    The unified diff text.
  """
  before = before.splitlines()
  after = after.splitlines()
  # filename = filename.decode('gbk')
  # filename = filename.encode('utf-8')
  # print str(filename)
  # print repr(filename)
  # print filename
  # return 1
  a = difflib.unified_diff(
          before,
          after,
          filename,
          filename,
          '(original)',
          '(reformatted)',
          lineterm='')
  o = ''
  for p in a:
    print repr(p),type(p)
    o += p + '\n'
  o += '\n'
  try:
    return '\n'.join(a) + '\n'
  except Exception as e:
    return None


D:\>yapf d:\测试\a.py
'--- d:\\\xb2\xe2\xca\xd4\\a.py\t(original)' <type 'str'>
'+++ d:\\\xb2\xe2\xca\xd4\\a.py\t(reformatted)' <type 'str'>
'@@ -1,3 +1,3 @@' <type 'str'>
u' a = 1' <type 'unicode'>

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\yapf.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\yapf\__init__.py", line 313, in run_main
    sys.exit(main(sys.argv))
  File "c:\python27\lib\site-packages\yapf\__init__.py", line 201, in main
    verbose=args.verbose)
  File "c:\python27\lib\site-packages\yapf\__init__.py", line 251, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "c:\python27\lib\site-packages\yapf\__init__.py", line 276, in _FormatFile
    logger=logging.warning)
  File "c:\python27\lib\site-packages\yapf\yapflib\yapf_api.py", line 91, in FormatFile
    verify=verify)
  File "c:\python27\lib\site-packages\yapf\yapflib\yapf_api.py", line 154, in FormatCode
    unformatted_source, reformatted_source, filename=filename)
  File "c:\python27\lib\site-packages\yapf\yapflib\yapf_api.py", line 300, in _GetUnifiedDiff
    o += p + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 7: ordinal not in range(128)


'@@ -1,3 +1,3 @@' <type 'str'>
u' a = 1' <type 'unicode'>
