### ISSUE TITLE
f+r string causes yapf to fail

### ISSUE THREAD

**Issue by ojarva** [google/yapf#632]
Test code:

```
b = "foo"
a = fr"^{b}\w$"
```

`yapf` output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib64/python3.6/lib2to3/pgen2/driver.py", line 107, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib64/python3.6/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib64/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value='"^{b}\\w$"', context=('', (2, 6))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yapf", line 11, in <module>
    load_entry_point('python3-yapf===0.24.0-15-g5b241d1', 'console_scripts', 'yapf')()
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 317, in run_main
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 205, in main
    verbose=args.verbose)
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 255, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 280, in _FormatFile
    logger=logging.warning)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 91, in FormatFile
    verify=verify)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 129, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib64/python3.6/lib2to3/pgen2/driver.py", line 107, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib64/python3.6/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib64/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value='"^{b}\\w$"', context=('', (2, 6))
```

With `--parallel` this causes more mysterious

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 272, in _queue_management_worker
    result_item = reader.recv()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'
```

Version info:
```
$ python --version
Python 3.6.6
$ yapf --version
yapf 0.24.0
```

**Comment by william-richard** [comment]
I'm getting this error on just r strings as well

**Comment by qwertystop** [comment]
I'm getting a similar error with `rb` strings:

`rb'Hours\s+(\d+.\d+)'`
produces
```
Traceback (most recent call last):
  File "/Users/dheyman/.pyenv/versions/3.5.2/envs/call-analytics/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Users/dheyman/.pyenv/versions/3.5.2/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Users/dheyman/.pyenv/versions/3.5.2/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Users/dheyman/.pyenv/versions/3.5.2/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'Hours\\s+(\\d+.\\d+)'", context=('', (160, 10))
```

(it does this even if the raw string doesn't actually contain backslashes, but works fine if it's just a bytestring and not a raw string)

```
$ python --version
Python 3.5.2
$ yapf --version
yapf 0.24.0
```

**Comment by SergiyKolesnikov** [comment]
A minimal example that triggers the error:
```
fr''
```

**Comment by sk-** [comment]
This is a duplicate of #537
