### ISSUE TITLE
Counterintuitive formatting of nested dicts

### ISSUE THREAD

**Issue by PetterS** [google/yapf#678]
I have the following code:
```
class A:
    def b():
        d = {
            "123456": [
                {
                    "12": "aa"
                },
                {
                    "12": "bb"
                },
                {
                    "12": "cc",
                    "1234567890": {
                        "1234567": [{
                            "12": "dd",
                            "12345": "text 1"
                        }, {
                            "12": "ee",
                            "12345": "text 2"
                        }]
                    }
                }
            ]
        }
```
Running `yapf -i ` on this file results in:
```
class A:
    def b():
        d = {
            "123456": [{
                "12": "aa"
            }, {
                "12": "bb"
            },
                       {
                           "12": "cc",
                           "1234567890": {
                               "1234567": [{
                                   "12": "dd",
                                   "12345": "text 1"
                               }, {
                                   "12": "ee",
                                   "12345": "text 2"
                               }]
                           }
                       }]
        }
```
What is going on here? The list contains three dicts, but the last one becomes more indented for some reason.

**Comment by gwelymernans** [comment]
I'm not sure. YAPF must be getting confused about the last dictionary entry. Try terminating the list with a comma:

```
                {
                    "12": "cc",
                    "1234567890": {
                        "1234567": [{
                            "12": "dd",
                            "12345": "text 1"
                        }, {
                            "12": "ee",
                            "12345": "text 2"
                        }]
                    }
                },  # <--- here
            ]
        }
```

**Comment by apbard** [comment]
This is a dup of #623
The source seems to be commit: ea904bd7f55fcea88e7ef3008dc5d23ac95758e0

**Comment by mithro** [comment]
I can confirm that reverting https://github.com/google/yapf/commit/ea904bd7f55fcea88e7ef3008dc5d23ac95758e0#diff-0bdae23a0b2120e515d6323786a08332 fixes the issue.

**Comment by mithro** [comment]
This patch adds a test which demonstrates the issue.

```patch
From b11763a53bca9296dd60e54c06e7f75d1876769d Mon Sep 17 00:00:00 2001
From: Tim 'mithro' Ansell <tansell@google.com>
Date: Wed, 20 Mar 2019 14:10:08 -0700
Subject: [PATCH 1/1] Adding test for Github Issue #678.

---
 yapftests/reformatter_buganizer_test.py | 27 +++++++++++++++++++++++++
 1 file changed, 27 insertions(+)

diff --git a/yapftests/reformatter_buganizer_test.py b/yapftests/reformatter_buganizer_test.py
index 22309ac..e7c05b0 100644
--- a/yapftests/reformatter_buganizer_test.py
+++ b/yapftests/reformatter_buganizer_test.py
@@ -236,6 +236,33 @@ for sssssss, aaaaaaaaaa in [
     uwlines = yapf_test_helper.ParseAndUnwrap(code)
     self.assertCodeEqual(code, reformatter.Reformat(uwlines))
 
+  def testB120771563(self):
+    code = """\
+class A:
+
+  def b():
+    d = {
+        "123456": [{
+            "12": "aa"
+        }, {
+            "12": "bb"
+        }, {
+            "12": "cc",
+            "1234567890": {
+                "1234567": [{
+                    "12": "dd",
+                    "12345": "text 1"
+                }, {
+                    "12": "ee",
+                    "12345": "text 2"
+                }]
+            }
+        }]
+    }
+"""
+    uwlines = yapf_test_helper.ParseAndUnwrap(code)
+    self.assertCodeEqual(code, reformatter.Reformat(uwlines))
+
   def testB79462249(self):
     code = """\
 foo.bar(baz, [
-- 
2.21.0.225.g810b269d1ac-goog
```

The output with this test added is;
```
tansell@tansell:~/github/mithro/yapf$ python setup.py test
running test
..............................................F.........................................................................................................sssssssssssssssssss........................................
.............................................................................................................................................................................................s...............s.....
..................................................................................................................
======================================================================
FAIL: testB120771563 (yapftests.reformatter_buganizer_test.BuganizerFixes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/tansell/github/mithro/yapf/yapftests/reformatter_buganizer_test.py", line 264, in testB120771563
    self.assertCodeEqual(code, reformatter.Reformat(uwlines))
  File "/usr/local/google/home/tansell/github/mithro/yapf/yapftests/yapf_test_helper.py", line 57, in assertCodeEqual
    self.fail('\n'.join(msg))
AssertionError: Code format mismatch:
Expected:
 > class A:
 > 
 >   def b():
 >     d = {
 >         "123456": [{
 >             "12": "aa"
 >         }, {
 >             "12": "bb"
 >         }, {
 >             "12": "cc",
 >             "1234567890": {
 >                 "1234567": [{
 >                     "12": "dd",
 >                     "12345": "text 1"
 >                 }, {
 >                     "12": "ee",
 >                     "12345": "text 2"
 >                 }]
 >             }
 >         }]
 >     }
Actual:
 > class A:
 > 
 >   def b():
 >     d = {
 >         "123456": [{
 >             "12": "aa"
 >         }, {
 >             "12": "bb"
 >         },
 >                    {
 >                        "12": "cc",
 >                        "1234567890": {
 >                            "1234567": [{
 >                                "12": "dd",
 >                                "12345": "text 1"
 >                            }, {
 >                                "12": "ee",
 >                                "12345": "text 2"
 >                            }]
 >                        }
 >                    }]
 >     }
Diff:
--- actual
+++ expected
@@ -6,17 +6,16 @@
             "12": "aa"
         }, {
             "12": "bb"
-        },
-                   {
-                       "12": "cc",
-                       "1234567890": {
-                           "1234567": [{
-                               "12": "dd",
-                               "12345": "text 1"
-                           }, {
-                               "12": "ee",
-                               "12345": "text 2"
-                           }]
-                       }
-                   }]
+        }, {
+            "12": "cc",
+            "1234567890": {
+                "1234567": [{
+                    "12": "dd",
+                    "12345": "text 1"
+                }, {
+                    "12": "ee",
+                    "12345": "text 2"
+                }]
+            }
+        }]
     }

----------------------------------------------------------------------
Ran 536 tests in 6.870s

FAILED (failures=1, skipped=21)
```

**Comment by mithro** [comment]
```patch
diff --git a/yapf/yapflib/format_decision_state.py b/yapf/yapflib/format_decision_state.py
index 8dd5e55..bd2bb9b 100644
--- a/yapf/yapflib/format_decision_state.py
+++ b/yapf/yapflib/format_decision_state.py
@@ -281,15 +281,6 @@ class FormatDecisionState(object):
             if not self._FitsOnLine(current, tok.matching_bracket):
               return True
 
-    if current.OpensScope() and previous.value == ',':
-      # If we have a list of tuples, then we can get a similar look as above. If
-      # the full list cannot fit on the line, then we want a split.
-      open_bracket = unwrapped_line.IsSurroundedByBrackets(current)
-      if (open_bracket and open_bracket.value in '[{' and
-          format_token.Subtype.SUBSCRIPT_BRACKET not in open_bracket.subtypes):
-        if not self._FitsOnLine(current, current.matching_bracket):
-          return True
-
     ###########################################################################
     # Dict/Set Splitting
     if (style.Get('EACH_DICT_ENTRY_ON_SEPARATE_LINE') and
```

Causes the following test to fail;
```
======================================================================
FAIL: testB80484938 (yapftests.reformatter_buganizer_test.BuganizerFixes)
----------------------------------------------------------------------
Traceback (most recent call last):                   
  File "/usr/local/google/home/tansell/github/mithro/yapf/yapftests/reformatter_buganizer_test.py", line 237, in testB80484938
    self.assertCodeEqual(code, reformatter.Reformat(uwlines))
  File "/usr/local/google/home/tansell/github/mithro/yapf/yapftests/yapf_test_helper.py", line 57, in assertCodeEqual
    self.fail('\n'.join(msg))
AssertionError: Code format mismatch:
Expected:                    
 > for sssssss, aaaaaaaaaa in [                                           
 >     ('ssssssssssssssssssss', 'sssssssssssssssssssssssss'),     
 >     ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
 >      'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'),                 
 >     ('pppppppppppppppppppppppppppp', 'pppppppppppppppppppppppppppppppp'),
 >     ('wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwwww'),
 >     ('sssssssssssssssss', 'sssssssssssssssssssssss'),     
 >     ('ggggggggggggggggggggggg', 'gggggggggggggggggggggggggggg'),
 >     ('ggggggggggggggggg', 'gggggggggggggggggggggg'),
 >     ('eeeeeeeeeeeeeeeeeeeeee', 'eeeeeeeeeeeeeeeeeeeeeeeeeee')
 > ]:                                                           
 >   pass                                                  
 >                                                                       
 > for sssssss, aaaaaaaaaa in [                                           
 >     ('ssssssssssssssssssss', 'sssssssssssssssssssssssss'),
 >     ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', 'nnnnnnnnnnnnnnnnnnnnnnnnn'),
 >     ('pppppppppppppppppppppppppppp', 'pppppppppppppppppppppppppppppppp'),
 >     ('wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwwww'),
 >     ('sssssssssssssssss', 'sssssssssssssssssssssss'),      
 >     ('ggggggggggggggggggggggg', 'gggggggggggggggggggggggggggg'),
 >     ('ggggggggggggggggg', 'gggggggggggggggggggggg'),
 >     ('eeeeeeeeeeeeeeeeeeeeee', 'eeeeeeeeeeeeeeeeeeeeeeeeeee')
 > ]:
 >   pass                                                             
 >                     
 > for sssssss, aaaaaaaaaa in [
 >     ('ssssssssssssssssssss', 'sssssssssssssssssssssssss'),
 >     ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',                                                                                                                                                                     
 >      'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'),                                                                                                                                                                 
 >     ('pppppppppppppppppppppppppppp', 'pppppppppppppppppppppppppppppppp'),
 >     ('wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwwww'),
 >     ('sssssssssssssssss', 'sssssssssssssssssssssss'),
 >     ('ggggggggggggggggggggggg', 'gggggggggggggggggggggggggggg'),
 >     ('ggggggggggggggggg', 'gggggggggggggggggggggg'),
 >     ('eeeeeeeeeeeeeeeeeeeeee', 'eeeeeeeeeeeeeeeeeeeeeeeeeee'),                         
 > ]:                        
 >   pass                                  
Actual:                                    
 > for sssssss, aaaaaaaaaa in [                        
 >     ('ssssssssssssssssssss',                                     
 >      'sssssssssssssssssssssssss'), ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
 >                                     'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'),
 >     ('pppppppppppppppppppppppppppp',                
 >      'pppppppppppppppppppppppppppppppp'), ('wwwwwwwwwwwwwwwwwwww',            
 >                                            'wwwwwwwwwwwwwwwwwwwwwwwww'),
 >     ('sssssssssssssssss',                                        
 >      'sssssssssssssssssssssss'), ('ggggggggggggggggggggggg',
 >                                   'gggggggggggggggggggggggggggg'),           
 >     ('ggggggggggggggggg',                                        
 >      'gggggggggggggggggggggg'), ('eeeeeeeeeeeeeeeeeeeeee',
 >                                  'eeeeeeeeeeeeeeeeeeeeeeeeeee')
 > ]:                                                                           
 >   pass                
 >                                                        
 > for sssssss, aaaaaaaaaa in [      
 >     ('ssssssssssssssssssss',
 >      'sssssssssssssssssssssssss'), ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
 >                                     'nnnnnnnnnnnnnnnnnnnnnnnnn'),
 >     ('pppppppppppppppppppppppppppp',
 >      'pppppppppppppppppppppppppppppppp'), ('wwwwwwwwwwwwwwwwwwww',
 >                                            'wwwwwwwwwwwwwwwwwwwwwwwww'),
 >     ('sssssssssssssssss',
 >      'sssssssssssssssssssssss'), ('ggggggggggggggggggggggg',
 >                                   'gggggggggggggggggggggggggggg'),
 >     ('ggggggggggggggggg',
 >      'gggggggggggggggggggggg'), ('eeeeeeeeeeeeeeeeeeeeee',
 >                                  'eeeeeeeeeeeeeeeeeeeeeeeeeee')
 > ]:
 >   pass
 >
 > for sssssss, aaaaaaaaaa in [
 >     ('ssssssssssssssssssss', 'sssssssssssssssssssssssss'),
 >     ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
 >      'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'),
 >     ('pppppppppppppppppppppppppppp', 'pppppppppppppppppppppppppppppppp'),
 >     ('wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwwww'),
 >     ('sssssssssssssssss', 'sssssssssssssssssssssss'),
 >     ('ggggggggggggggggggggggg', 'gggggggggggggggggggggggggggg'),
 >     ('ggggggggggggggggg', 'gggggggggggggggggggggg'),
 >     ('eeeeeeeeeeeeeeeeeeeeee', 'eeeeeeeeeeeeeeeeeeeeeeeeeee'),
 > ]:
 >   pass
Diff:
--- actual
+++ expected
@@ -1,32 +1,25 @@
 for sssssss, aaaaaaaaaa in [
-    ('ssssssssssssssssssss',
-     'sssssssssssssssssssssssss'), ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
-                                    'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'),
-    ('pppppppppppppppppppppppppppp',
-     'pppppppppppppppppppppppppppppppp'), ('wwwwwwwwwwwwwwwwwwww',
-                                           'wwwwwwwwwwwwwwwwwwwwwwwww'),
-    ('sssssssssssssssss',
-     'sssssssssssssssssssssss'), ('ggggggggggggggggggggggg',
-                                  'gggggggggggggggggggggggggggg'),
-    ('ggggggggggggggggg',
-     'gggggggggggggggggggggg'), ('eeeeeeeeeeeeeeeeeeeeee',
-                                 'eeeeeeeeeeeeeeeeeeeeeeeeeee')
+    ('ssssssssssssssssssss', 'sssssssssssssssssssssssss'),
+    ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
+     'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn'),
+    ('pppppppppppppppppppppppppppp', 'pppppppppppppppppppppppppppppppp'),
+    ('wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwwww'),
+    ('sssssssssssssssss', 'sssssssssssssssssssssss'),
+    ('ggggggggggggggggggggggg', 'gggggggggggggggggggggggggggg'),
+    ('ggggggggggggggggg', 'gggggggggggggggggggggg'),
+    ('eeeeeeeeeeeeeeeeeeeeee', 'eeeeeeeeeeeeeeeeeeeeeeeeeee')
 ]:
   pass

 for sssssss, aaaaaaaaaa in [
-    ('ssssssssssssssssssss',
-     'sssssssssssssssssssssssss'), ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
-                                    'nnnnnnnnnnnnnnnnnnnnnnnnn'),
-    ('pppppppppppppppppppppppppppp',
-     'pppppppppppppppppppppppppppppppp'), ('wwwwwwwwwwwwwwwwwwww',
-                                           'wwwwwwwwwwwwwwwwwwwwwwwww'),
-    ('sssssssssssssssss',
-     'sssssssssssssssssssssss'), ('ggggggggggggggggggggggg',
-                                  'gggggggggggggggggggggggggggg'),
-    ('ggggggggggggggggg',
-     'gggggggggggggggggggggg'), ('eeeeeeeeeeeeeeeeeeeeee',
-                                 'eeeeeeeeeeeeeeeeeeeeeeeeeee')
+    ('ssssssssssssssssssss', 'sssssssssssssssssssssssss'),
+    ('nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', 'nnnnnnnnnnnnnnnnnnnnnnnnn'),
+    ('pppppppppppppppppppppppppppp', 'pppppppppppppppppppppppppppppppp'),
+    ('wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwwww'),
+    ('sssssssssssssssss', 'sssssssssssssssssssssss'),
+    ('ggggggggggggggggggggggg', 'gggggggggggggggggggggggggggg'),
+    ('ggggggggggggggggg', 'gggggggggggggggggggggg'),
+    ('eeeeeeeeeeeeeeeeeeeeee', 'eeeeeeeeeeeeeeeeeeeeeeeeeee')
 ]:
   pass


----------------------------------------------------------------------
Ran 536 tests in 8.589s

FAILED (failures=1, skipped=5)
```

**Comment by mithro** [comment]
What I don't understand is why it gets the first two elements correct and then fails on the 3rd element? This makes me feel that a different path is being taken on the 3rd element which hits the new code.

I'm wondering if this has something to do with `OpensScope()` interaction?

**Comment by gwelymernans** [comment]
What the patch above is doing is looking at the element in the list/set/dictionary and seeing if it fits on a single line. If it doesn't then yapf decides to split at that point. The first two elements in your example do fit on a single line so they aren't split. However, the last one doesn't fit.

*BUT* it's okay that it doesn't fit, because it's a dictionary and those behave in strange ways. This might help. It's a bit of a hack, but you can see where this is going I think:

```
diff --git a/yapf/yapflib/format_decision_state.py b/yapf/yapflib/format_decision_state.py
index 486be8b..46c51a9 100644
--- a/yapf/yapflib/format_decision_state.py
+++ b/yapf/yapflib/format_decision_state.py
@@ -281,7 +281,10 @@ class FormatDecisionState(object):
             if not self._FitsOnLine(current, tok.matching_bracket):
               return True
 
-    if current.OpensScope() and previous.value == ',':
+    if (current.OpensScope() and previous.value == ',' and not (
+            current.value == '{' and
+            format_token.Subtype.DICTIONARY_KEY in current.next_token.subtypes
+    )):
       # If we have a list of tuples, then we can get a similar look as above. If
       # the full list cannot fit on the line, then we want a split.
       open_bracket = unwrapped_line.IsSurroundedByBrackets(current)
```

**Comment by mithro** [comment]
@gwelymernans Your change makes all the tests pass...

**Comment by mithro** [comment]
https://github.com/google/yapf/compare/master...mithro:master
