### ISSUE TITLE
Backslash shouldn't require escaping when reading from stdin

### ISSUE THREAD

**Issue by nickhutchinson** [google/yapf#70]
yapf appears to interpret '\' as an escape character when reading from stdin.

```
> echo 's = "foo\\nbar"' | cat
s = "foo\\nbar"
> echo 's = "foo\nbar"' | cat
s = "foo\nbar"
```

but...

```
> echo 's = "foo\\nbar"' | yapf
s = "foo\nbar"
> echo 's = "foo\nbar"' | yapf
Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 9, in <module>
    load_entry_point('yapf==0.1', 'console_scripts', 'yapf')()
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 170, in run_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 111, in main
    verify=args.verify))
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 101, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/pytree_utils.py", line 100, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/parse.py", line 116, in addtoken
    ilabel = self.classify(type, value, context)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/parse.py", line 172, in classify
    raise ParseError("bad token", type, value, context)
lib2to3.pgen2.parse.ParseError: bad token: type=56, value=u' ', context=('', (1, 3))
```

**Comment by eliben** [comment]
Do you also get that when processing a file?

**Comment by nickhutchinson** [comment]
Reading from a file works fine.
```
> cat > test.py <<EOF
> foo = "bar\nbaz"
> EOF
> cat test.py
foo = "bar\nbaz"
> yapf test.py
foo = "bar\nbaz"
> yapf test.py
foo = "bar\nbaz"
```

**Comment by eliben** [comment]
Yep, I can reproduce it too.

Thanks for the report!

**Comment by gwelymernans** [comment]
@eliben, any thoughts on how to address this? :-)

**Comment by eliben** [comment]
@pignacio pointed a possible cause in #79 -- I'll take a look
