### ISSUE TITLE
TypeError:  spaces_before_comment 

### ISSUE THREAD

**Issue by butuzov** [google/yapf#723]
Running `yapf --style-help` alongside with having enabled `space_before_comment` with range values generates TypeError

**Example Config (setup.cfg)**
```ini
[yapf]
spaces_before_comment                             = 10, 30
```
**Test Run**
```bash
> yapf --style-help
....
Correct output
....
#   short                                                       # This is a shorter statement
#
Traceback (most recent call last):
  File "/Users/butuzov/Desktop/doc.md/.venv/bin/yapf", line 10, in <module>
    sys.exit(run_main())
  File "/Users/butuzov/Desktop/doc.md/.venv/lib/python3.7/site-packages/yapf/__init__.py", line 336, in run_main
    sys.exit(main(sys.argv))
  File "/Users/butuzov/Desktop/doc.md/.venv/lib/python3.7/site-packages/yapf/__init__.py", line 153, in main
    option_value = ', '.join(option_value)
TypeError: sequence item 0: expected str instance, int found
```

Python 3.7
Platform Darwin.

**Comment by butuzov** [comment]
solved
