### ISSUE TITLE
Recursive mode doesn't work on network shares

### ISSUE THREAD

**Issue by samuela** [google/yapf#734]
I need to run yapf on some code stored on a network drive. I have an SMB drive mounted and standard yapf commands without the `--recursive` flag work great. However using `--recursive` makes things hang indefinitely:

```
$ pipenv run yapf --recursive .
^CTraceback (most recent call last):
  File "/Users/skainswo/.local/share/virtualenvs/research-OGGq2tNy/bin/yapf", line 10, in <module>
    sys.exit(run_main())
  File "/Users/skainswo/.local/share/virtualenvs/research-OGGq2tNy/lib/python3.7/site-packages/yapf/__init__.py", line 335, in run_main
    sys.exit(main(sys.argv))
  File "/Users/skainswo/.local/share/virtualenvs/research-OGGq2tNy/lib/python3.7/site-packages/yapf/__init__.py", line 207, in main
    exclude_patterns_from_ignore_file)
  File "/Users/skainswo/.local/share/virtualenvs/research-OGGq2tNy/lib/python3.7/site-packages/yapf/yapflib/file_resources.py", line 110, in GetCommandLineFiles
    return _FindPythonFiles(command_line_file_list, recursive, exclude)
  File "/Users/skainswo/.local/share/virtualenvs/research-OGGq2tNy/lib/python3.7/site-packages/yapf/yapflib/file_resources.py", line 172, in _FindPythonFiles
    if IsPythonFile(filepath):
  File "/Users/skainswo/.local/share/virtualenvs/research-OGGq2tNy/lib/python3.7/site-packages/yapf/yapflib/file_resources.py", line 198, in IsPythonFile
    encoding = tokenize.detect_encoding(fd.readline)[0]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/tokenize.py", line 290, in detect_encoding
    first = read_or_stop()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib2to3/pgen2/tokenize.py", line 264, in read_or_stop
    return readline()
KeyboardInterrupt
```

The exact same setup works without a hitch on the local filesystem (same files, same yapf version). I'm running on macOS 10.14.4 with yapf 0.27.0.

**Comment by gwelymernans** [comment]
I'm not familiar with SMB drives. It looks like it's hanging in `lib2to3` when calling `readline` on a filehandle from the `open` command. If you change the `open` in `file_resources.py:197` to something like `py3compat.open_with_encoding()` does it work?

**Comment by samuela** [comment]
I believe it may in fact be working but just slow as molasses. I just tried waiting much, much longer and I'm now seeing a new error:
```
$ python3 -m yapf --exclude "._*" --recursive --diff /Users/skainswo/nu/skainswo/research/
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/skainswo/dev/yapf/yapf/__main__.py", line 18, in <module>
    yapf.run_main()
  File "/Users/skainswo/dev/yapf/yapf/__init__.py", line 335, in run_main
    sys.exit(main(sys.argv))
  File "/Users/skainswo/dev/yapf/yapf/__init__.py", line 220, in main
    verbose=args.verbose)
  File "/Users/skainswo/dev/yapf/yapf/__init__.py", line 270, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/Users/skainswo/dev/yapf/yapf/__init__.py", line 296, in _FormatFile
    logger=logging.warning)
  File "/Users/skainswo/dev/yapf/yapf/yapflib/yapf_api.py", line 84, in FormatFile
    original_source, newline, encoding = ReadFile(filename, logger)
  File "/Users/skainswo/dev/yapf/yapf/yapflib/yapf_api.py", line 196, in ReadFile
    lines = fd.readlines()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 709, in readlines
    return self.reader.readlines(sizehint)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 618, in readlines
    data = self.read()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```
