### ISSUE TITLE
yapf crashes on valid conditional assignment from Python 3.8

### ISSUE THREAD

**Issue by tdemin** [google/yapf#856]
* **Python**: 3.8.2
* **yapf**: 0.30.0

The relevant snippet is

```py
def json(self) -> JSONTask:
        result: JSONTask = {
            "id": self.id,
            "text": self.text,
            "status": self.status,
            "last_mod": self.last_mod_time
        }
        for i in "parent_id", "deadline", "reminder":
            if x := getattr(self , i):
                result[i] = x  # type: ignore
        return result
```

yapf will crash with this stacktrace:

```
% yapf
def json(self) -> JSONTask:
        result: JSONTask = {
            "id": self.id,
            "text": self.text,
            "status": self.status,
            "last_mod": self.last_mod_time
        }
        for i in "parent_id", "deadline", "reminder":
            if x := getattr(self, i):
                # gotta love how we suppress mypy in the exact places it
                # is supposed to type check.
                result[i] = x  # type: ignore
        return result
<hit Ctrl+D>
Traceback (most recent call last):
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/tdemin/.pyenv/versions/3.8.2/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/tdemin/.pyenv/versions/3.8.2/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/tdemin/.pyenv/versions/3.8.2/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=22, value='=', context=('', (9, 18))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/bin/yapf", line 10, in <module>
    sys.exit(run_main())
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/lib/python3.8/site-packages/yapf/__init__.py", line 365, in run_main
    sys.exit(main(sys.argv))
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/lib/python3.8/site-packages/yapf/__init__.py", line 103, in main
    reformatted_source, _ = yapf_api.FormatCode(
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/tdemin/.pyenv/versions/3.8.2/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/tdemin/.pyenv/versions/3.8.2/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/tdemin/.pyenv/versions/3.8.2/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=22, value='=', context=('', (9, 18))
```

Reworking the part with `:=` into this code:

```
x = getattr(...)
if x:
```

works just fine. Probably not relevant, but here's the relevant part of `setup.cfg`:

```cfg
[yapf]
based_on_style = pep8
split_before_logical_operator = true
blank_line_before_nested_class_or_def = false
coalesce_brackets = true
dedent_closing_brackets = true
indent_closing_brackets = false
indent_width = 4
use_tabs = false
column_limit = 100
```

This is reproducible on both the original file and only feeding yapf the snippet above via CLI.

**Comment by gwelymernans** [comment]
This is due to yapf using lib2to3 for parsing, which doesn't support everything in newer versions of python.

We really need a new parser strategy.

**Comment by kamahen** [comment]
"We really need a new parser strategy."

So far, nobody has responded to my suggestion of wrapping library(ast) with "whitespace" information, so I haven't done anything. If there's enough interest, I'll seriously consider working on it.

**Comment by gwelymernans** [comment]
I looked into using "ast" and "tokenize" as well. I think they would be a good replacement. I just haven't had cycles to work on it further. But yes I'm interested in it. :-)

**Comment by kamahen** [comment]
Nobody has replied to https://mail.python.org/archives/list/python-ideas@python.org/message/X2HJ6I6XLIGRZDB27HRHIVQC3RXNZAY4/
or https://bugs.python.org/issue40360
or emails I sent to a few other places.

If only yapf uses my work, that's not enough justification for the effort. :(

**Comment by gwelymernans** [comment]
@kamahen I understand. :-(

**Comment by tirkarthi** [comment]
lib2to3 now seems to support walrus operator https://bugs.python.org/issue36541 . see also https://github.com/google/yapf/issues/787
