### ISSUE TITLE
match case statement raise lib2to3.pgen2.parse.ParseError: bad input

### ISSUE THREAD

**Issue by heavenshell** [google/yapf#983]
Hi.

Using Python3.10 match case raise exception.
Version: yapf-0.31.0

```python
def http_error(status):
    match status:
        case _:
            return ""
```

```
Traceback (most recent call last):
  File "tmp/.venv/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='status', context=(' ', (2, 10))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.venv/bin/yapf", line 8, in <module>
    sys.exit(run_main())
  File "tmp/.venv/lib/python3.10/site-packages/yapf/__init__.py", line 362, in run_main
    sys.exit(main(sys.argv))
  File "tmp/.venv/lib/python3.10/site-packages/yapf/__init__.py", line 126, in main
    changed = FormatFiles(
  File "tmp/.venv/lib/python3.10/site-packages/yapf/__init__.py", line 204, in FormatFiles
    changed |= _FormatFile(filename, lines, style_config, no_local_style,
  File "tmp/.venv/lib/python3.10/site-packages/yapf/__init__.py", line 227, in _FormatFile
    reformatted_code, encoding, has_change = yapf_api.FormatFile(
  File "tmp/.venv/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 94, in FormatFile
    reformatted_source, changed = FormatCode(
  File "tmp/.venv/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "tmp/.venv/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='status', context=(' ', (2, 10))
```

https://github.com/google/yapf/issues/966#issuecomment-933630210 
This report says, hacking Grammer.txt works well, but I don't want to hack Grammer.txt

Thank you.

**Comment by char101** [comment]
It is impossible to support match statement without modifying Grammar.txt.

If you simply do not want to modify the builtin library you can use my fork until it is supported officially

https://github.com/char101/yapf/tree/3.10

**Comment by j2kun** [comment]
Looks like this is still an issue despite "Add support for Python 3.10" above.

Now the error further fails to format for display, with the stack trace

```
Traceback (most recent call last):
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='value', context=(' ', (3, 6))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.10/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.10/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.10/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='value', context=(' ', (3, 6))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/__init__.py", line 225, in _FormatFile
    reformatted_code, encoding, has_change = yapf_api.FormatFile(
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 96, in FormatFile
    reformatted_source, changed = FormatCode(
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j2kun/dotfiles/.config/nvim/venv/bin/yapf", line 8, in <module>
    sys.exit(run_main())
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/__init__.py", line 360, in run_main
    sys.exit(main(sys.argv))
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/__init__.py", line 124, in main
    changed = FormatFiles(
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/__init__.py", line 202, in FormatFiles
    changed |= _FormatFile(filename, lines, style_config, no_local_style,
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/__init__.py", line 236, in _FormatFile
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/home/j2kun/dotfiles/.config/nvim/venv/lib/python3.10/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range
```

When run on file

```
value = 5

match value:
    case 5:
        print('wat')
```
