### ISSUE TITLE
Small bug: yapf crashes if there's a trailing comma after a dataclass attribute

### ISSUE THREAD

**Issue by BlakeJC94** [google/yapf#998]
Ran into this issue when debugging yapf a little while ago. This is not high priority, but it might be nice to catch this error before yapf crashes for the user.

Example code:
```python
# scratch.py
from dataclasses import dataclass, field
@dataclass
class A:
    x: int = field(default=1),
    y: int = field(default=2)
```

Expected output:
```python
from dataclasses import dataclass, field


@dataclass
class A:
    x: int = field(default=1),
    y: int = field(default=2)
```

<details>
<summary>Error details</summary>

```bash 
$ python3 -m yapf scratch.py
Traceback (most recent call last):
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=12, value=',', context=('', (4, 29))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=12, value=',', context=('', (4, 29))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/__init__.py", line 225, in _FormatFile
    reformatted_code, encoding, has_change = yapf_api.FormatFile(
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 96, in FormatFile
    reformatted_source, changed = FormatCode(
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/__main__.py", line 18, in <module>
    yapf.run_main()
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/__init__.py", line 360, in run_main
    sys.exit(main(sys.argv))
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/__init__.py", line 124, in main
    changed = FormatFiles(
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/__init__.py", line 202, in FormatFiles
    changed |= _FormatFile(filename, lines, style_config, no_local_style,
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/__init__.py", line 236, in _FormatFile
    raise errors.YapfError(errors.FormatErrorMsg(e))
  File "/home/blake/.pyenv/versions/3.8.11/lib/python3.8/site-packages/yapf/yapflib/errors.py", line 37, in FormatErrorMsg
    return '{}:{}:{}: {}'.format(e.args[1][0], e.args[1][1], e.args[1][2], e.msg)
IndexError: tuple index out of range
```

</details>

The issue is resolved by removing the trailing comma on the declaration of `x`

OS version: `Pop!_OS 21.10 x86_64` (Ubuntu-based)
Python version: `Python 3.8.11`
Yapf version: `yapf 0.32.0`

**Comment by SolitaryThinker** [comment]
+1 ran into this

**Comment by Edenzzzz** [comment]
This seems still not fixed...
